export {
  OWNER_ROLE_NAME,
  ADMIN_ROLE_NAME,
  MEMBER_ROLE_NAME,
  TECHNICIAN_ROLE_NAME,
  DISPATCHER_ROLE_NAME,
  PLATFORM_OWNER_ROLE_NAME,
  COMPANY_OWNER_ROLE_NAME,
  MANAGER_ROLE_NAME,
  ACCOUNTANT_ROLE_NAME,
  CLIENT_ROLE_NAME,
  LEGACY_OWNER_ROLE_NAME,
  LEGACY_ADMIN_ROLE_NAME,
  LEGACY_MEMBER_ROLE_NAME,
  OWNER_PERMISSIONS,
  ADMIN_PERMISSIONS,
  MEMBER_PERMISSIONS,
  TECHNICIAN_PERMISSIONS,
  DISPATCHER_PERMISSIONS,
  MANAGER_PERMISSIONS,
  ACCOUNTANT_PERMISSIONS,
  CLIENT_PERMISSIONS,
  PLATFORM_OWNER_PERMISSIONS,
  COMPANY_OWNER_PERMISSIONS,
  PLATFORM_CROSS_TENANT_PERMISSION,
  DEFAULT_TEAM_ROLES,
  ROLE_MATRIX,
  LEGACY_ROLE_ALIASES,
  NON_ASSIGNABLE_ROLE_NAMES,
  INVITE_BLOCKED_ROLE_NAMES,
  INVITE_ALLOWED_ROLE_NAMES,
  MANUAL_ASSIGNABLE_ROLE_NAMES,
  PENDING_USER_MAPPING_DECISIONS,
  BINDING_ROLE_MIGRATION_DECISIONS,
  hasPermission,
  hasAnyPermission,
  hasAgentManagePermission,
  type Permission,
  type CanonicalRoleName,
  type RoleTemplate,
} from './permissions.js';
export {
  resolveStaffExperience,
  isPlatformOwner,
  isPlatformOwnerRole,
  isCompanyOwnerRole,
  isManagerRole,
  isAccountantRole,
  isDispatcherRole,
  isTechnicianRole,
  isClientRole,
  hasUnrestrictedCompanyAccess,
  hasCrossTenantPlatformAccess,
  getStaffHomePath,
  canAccessOwnerModule,
  canAccessTechnicianMobile,
  canAccessTenant,
  resolveCanonicalRoleName,
  isAssignableRoleName,
  isInviteAssignableRoleName,
  isCompanyOwnerRoleName,
  canAssignRoleName,
  TECHNICIAN_DENIED_PERMISSIONS,
  type StaffExperience,
  type StaffIdentity,
} from './role-experience.js';
export { hashPassword, verifyPassword, validatePasswordStrength } from './password.js';
export {
  createAccessToken,
  verifyAccessToken,
  generateRefreshToken,
  hashRefreshToken,
  REFRESH_TOKEN_TTL_MS,
  type AccessTokenPayload,
} from './tokens.js';
export {
  createPortalAccessToken,
  verifyPortalAccessToken,
  type PortalAccessTokenPayload,
} from './portal-tokens.js';
export { generateInviteToken, hashInviteToken, INVITE_TOKEN_TTL_MS } from './invites.js';
export { slugifyCompanyName, withUniqueSuffix } from './slug.js';
