export const OWNER_ROLE_NAME = 'Owner';

export const ADMIN_ROLE_NAME = 'Admin';

export const MEMBER_ROLE_NAME = 'Member';

/** Owner role receives wildcard — full access within the tenant. */
export const OWNER_PERMISSIONS = ['*'] as const;

export const ADMIN_PERMISSIONS = [
  'company:manage',
  'users:read',
  'users:manage',
  'settings:manage',
  'customers:read',
  'customers:write',
  'jobs:read',
  'jobs:write',
  'dispatch:read',
  'dispatch:write',
  'finance:read',
  'finance:write',
  'inventory:read',
  'inventory:write',
  'fleet:read',
  'fleet:write',
  'integrations:read',
  'integrations:manage',
  'communications:read',
  'communications:write',
  'communications:manage',
  'documents:read',
  'documents:write',
  'automation:read',
  'automation:write',
  'agents:read',
  'agents:write',
  'recruiting:read',
  'recruiting:write',
  'intelligence:read',
  'intelligence:write',
  'analytics:read',
  'analytics:write',
  'mobile:read',
  'mobile:write',
  'mobile:manage',
  'orchestration:read',
  'orchestration:write',
  'sales:read',
  'sales:write',
  'marketing:read',
  'marketing:write',
  'leads:read',
  'leads:write',
  'voice:read',
  'voice:write',
  'voice_reception:read',
  'voice_reception:write',
  'voice_reception:manage',
  'document_ai:read',
  'document_ai:write',
  'document_ai:manage',
  'business_continuity:read',
  'business_continuity:write',
  'business_continuity:manage',
  'search:read',
  'search:write',
  'search:manage',
  'data_migration:read',
  'data_migration:write',
  'data_migration:manage',
  'notifications:read',
  'notifications:write',
  'notifications:manage',
  'platform_health:read',
  'platform_health:write',
  'platform_health:manage',
  'launch_center:read',
  'launch_center:write',
  'launch_center:manage',
  'release_center:read',
  'release_center:write',
  'release_center:manage',
  'production_launch:read',
  'production_launch:write',
  'production_launch:manage',
  'release_manager:read',
  'release_manager:write',
  'release_manager:manage',
  'customer_support:read',
  'customer_support:write',
  'workforce:read',
  'workforce:write',
  'procurement:read',
  'procurement:write',
  'executive:read',
  'executive:write',
  'knowledge:read',
  'knowledge:write',
  'bi:read',
  'bi:write',
  'portal:read',
  'portal:manage',
  'customer_experience:read',
  'customer_experience:write',
  'customer_experience:manage',
  'quality:read',
  'quality:write',
  'communications_intelligence:read',
  'communications_intelligence:write',
  'asset_equipment:read',
  'asset_equipment:write',
  'asset_lifecycle:read',
  'asset_lifecycle:write',
  'asset_lifecycle:manage',
  'workforce_intelligence:read',
  'workforce_intelligence:write',
  'workforce_intelligence:manage',
  'legal_compliance:read',
  'legal_compliance:write',
  'legal_compliance:manage',
  'financial_planning:read',
  'financial_planning:write',
  'financial_planning:manage',
  'sales_intelligence:read',
  'sales_intelligence:write',
  'sales_intelligence:manage',
  'marketing_intelligence:read',
  'marketing_intelligence:write',
  'marketing_intelligence:manage',
  'service_delivery:read',
  'service_delivery:write',
  'service_delivery:manage',
  'it_operations:read',
  'it_operations:write',
  'it_operations:manage',
  'business_evolution:read',
  'business_evolution:write',
  'business_evolution:manage',
  'app_builder:read',
  'app_builder:write',
  'app_builder:manage',
  'industry_packs:read',
  'industry_packs:write',
  'industry_packs:manage',
  'public_developer:read',
  'public_developer:write',
  'public_developer:manage',
  'saas_management:read',
  'saas_management:write',
  'saas_management:manage',
  'voice_reception:read',
  'voice_reception:write',
  'voice_reception:manage',
  'ai_orchestration:read',
  'ai_orchestration:write',
  'dispatch_intelligence:read',
  'dispatch_intelligence:write',
  'fleet_intelligence:read',
  'fleet_intelligence:write',
  'personal_communications:read',
  'personal_communications:write',
  'security:read',
  'security:write',
  'platform:read',
  'platform:manage',
  'saas:read',
  'saas:manage',
  'ops:read',
  'ops:manage',
] as const;

export const MEMBER_PERMISSIONS = [
  'users:read',
  'customers:read',
  'jobs:read',
  'dispatch:read',
  'finance:read',
  'inventory:read',
  'fleet:read',
  'integrations:read',
  'communications:read',
  'documents:read',
  'automation:read',
  'agents:read',
  'recruiting:read',
  'intelligence:read',
  'analytics:read',
  'mobile:read',
  'orchestration:read',
  'sales:read',
  'marketing:read',
  'leads:read',
  'voice:read',
  'voice_reception:read',
  'document_ai:read',
  'business_continuity:read',
  'search:read',
  'data_migration:read',
  'notifications:read',
  'platform_health:read',
  'launch_center:read',
  'release_center:read',
  'production_launch:read',
  'release_manager:read',
  'customer_support:read',
  'workforce:read',
  'procurement:read',
  'executive:read',
  'knowledge:read',
  'bi:read',
  'portal:read',
  'quality:read',
  'communications_intelligence:read',
  'asset_equipment:read',
  'ai_orchestration:read',
  'dispatch_intelligence:read',
  'fleet_intelligence:read',
  'personal_communications:read',
  'security:read',
  'platform:read',
  'saas:read',
] as const;

export type Permission =
  | (typeof OWNER_PERMISSIONS)[number]
  | (typeof ADMIN_PERMISSIONS)[number]
  | (typeof MEMBER_PERMISSIONS)[number]
  | '*';

export const DEFAULT_TEAM_ROLES = [
  {
    name: OWNER_ROLE_NAME,
    permissions: [...OWNER_PERMISSIONS],
    isSystem: true,
  },
  {
    name: ADMIN_ROLE_NAME,
    permissions: [...ADMIN_PERMISSIONS],
    isSystem: true,
  },
  {
    name: MEMBER_ROLE_NAME,
    permissions: [...MEMBER_PERMISSIONS],
    isSystem: true,
  },
] as const;

export function hasPermission(userPermissions: string[], required: string): boolean {
  if (userPermissions.includes('*')) {
    return true;
  }

  return userPermissions.includes(required);
}

export function hasAnyPermission(userPermissions: string[], required: string[]): boolean {
  return required.some((permission) => hasPermission(userPermissions, permission));
}
