packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': ^22.15.21
  '@types/react': ^19.1.2
  '@types/react-dom': ^19.1.2
  '@vitejs/plugin-react': ^4.4.1
  clsx: ^2.1.1
  drizzle-orm: ^0.44.2
  express: ^5.1.0
  pino: ^9.7.0
  pino-pretty: ^13.0.0
  react: ^19.1.0
  react-dom: ^19.1.0
  tailwindcss: ^4.1.7
  '@tailwindcss/vite': ^4.1.7
  tsx: ^4.19.4
  typescript: ~5.8.3
  prettier: ^3.5.3
  vite: ^6.3.5
  wouter: ^3.7.0
  zod: ^3.25.28

autoInstallPeers: false

onlyBuiltDependencies:
  - esbuild
