import { and, desc, eq, sql } from 'drizzle-orm';
import { isCompanyOwnerRole } from '@titan/auth';
import { AURA_NETWORK_CATALOG, isAllowedContextDomain, isForbiddenContextDomain, messageRequiresOwnerApproval, type AuraNetworkAgentKey, type AuraNetworkMessageKind } from '@titan/shared';
import type { DatabaseClient } from '@titan/db';
import { agentProfiles, auraCommandAgentRegistry, auraNetworkActivity, auraNetworkAgents, auraNetworkApprovals, auraNetworkContextAccessLogs, auraNetworkMessages, auraNetworkWorkflowRuns, auraNetworkWorkflowTasks, auraNetworkWorkflows, securityAuditLogs } from '@titan/db';
export class AuraAgentNetworkError extends Error { constructor(public readonly code:string,message:string){super(message);} }
export type AuraAgentNetworkActor={companyId:string;userId:string;roleName:string;permissions:string[]};
const owner=(a:AuraAgentNetworkActor)=>{if(!isCompanyOwnerRole({roleName:a.roleName,permissions:a.permissions}))throw new AuraAgentNetworkError('FORBIDDEN','Only the company Owner may perform this AURA Agent Network action');};
const iso=(d:Date|null|undefined)=>d?.toISOString()??null;
export class AuraAgentNetworkService {
 constructor(private readonly deps:{db:DatabaseClient}){}
 private async audit(a:AuraAgentNetworkActor,action:string,id:string|null,category:'ai'|'workflow'='ai'){await this.deps.db.insert(securityAuditLogs).values({companyId:a.companyId,userId:a.userId,category,action,entityType:'aura_agent_network',entityId:id,metadata:{autoExecuted:false,neverSourcesPersonalWhatsappPrivate:true,noDemoData:true}});}
 async ensureRegistry(a:AuraAgentNetworkActor){owner(a); const cc=await this.deps.db.query.auraCommandAgentRegistry.findMany({where:eq(auraCommandAgentRegistry.companyId,a.companyId)}); const profiles=await this.deps.db.query.agentProfiles.findMany({where:eq(agentProfiles.companyId,a.companyId)}); const existing=await this.deps.db.query.auraNetworkAgents.findMany({where:eq(auraNetworkAgents.companyId,a.companyId)}); const have=new Set(existing.map(x=>x.agentKey)); const rows=AURA_NETWORK_CATALOG.filter(x=>!have.has(x.agentKey)).map(x=>({companyId:a.companyId,agentKey:x.agentKey,linkedAgentKey:x.linkedAgentKey,linkedCommandRegistryId:cc.find(c=>c.agentKey===x.agentKey)?.id??null,linkedAgentProfileId:profiles.find(p=>p.agentKey===x.linkedAgentKey)?.id??null,status:'active' as const,createdByUserId:a.userId})); if(rows.length) await this.deps.db.insert(auraNetworkAgents).values(rows); await this.deps.db.update(auraCommandAgentRegistry).set({status:'active',updatedByUserId:a.userId,updatedAt:new Date()}).where(eq(auraCommandAgentRegistry.companyId,a.companyId)); await this.audit(a,'aura_agent_network.registry.ensured',null); return this.listRegistry(a); }
 async listRegistry(a:AuraAgentNetworkActor){return this.deps.db.query.auraNetworkAgents.findMany({where:eq(auraNetworkAgents.companyId,a.companyId),orderBy:[desc(auraNetworkAgents.createdAt)]});}
 async getMonitorOverview(a:AuraAgentNetworkActor){const [messages,workflows,runs,approvals]=await Promise.all([this.count(a,auraNetworkMessages),this.count(a,auraNetworkWorkflows),this.count(a,auraNetworkWorkflowRuns),this.deps.db.select({count:sql<number>`count(*)::int`}).from(auraNetworkApprovals).where(and(eq(auraNetworkApprovals.companyId,a.companyId),eq(auraNetworkApprovals.status,'awaiting_approval')))]); await this.audit(a,'aura_agent_network.monitor.read',null); return {counts:{messages,workflows,runs,pendingApprovals:approvals[0]?.count??0},guarantees:(await import('@titan/shared')).AURA_AGENT_NETWORK_GUARANTEES};}
 async listMessages(a:AuraAgentNetworkActor){return this.deps.db.query.auraNetworkMessages.findMany({where:eq(auraNetworkMessages.companyId,a.companyId),orderBy:[desc(auraNetworkMessages.createdAt)],limit:100});}
 async createMessage(a:AuraAgentNetworkActor,input:{fromAgentKey:AuraNetworkAgentKey;toAgentKey:AuraNetworkAgentKey;kind:AuraNetworkMessageKind;subject:string;body:string;contextDomain?:string}){owner(a);if(input.contextDomain&&isForbiddenContextDomain(input.contextDomain))throw new AuraAgentNetworkError('VALIDATION','Personal WhatsApp private context is forbidden');const approval=messageRequiresOwnerApproval(input.kind);const [row]=await this.deps.db.insert(auraNetworkMessages).values({...input,companyId:a.companyId,status:approval?'awaiting_approval':'draft',autoExecuted:false,createdByUserId:a.userId}).returning();if(approval)await this.createApproval(a,'handoff','aura_network_message',row.id);await this.audit(a,'aura_agent_network.message.created',row.id);return row;}
 async listWorkflows(a:AuraAgentNetworkActor){return this.deps.db.query.auraNetworkWorkflows.findMany({where:eq(auraNetworkWorkflows.companyId,a.companyId),orderBy:[desc(auraNetworkWorkflows.createdAt)]});}
 async createWorkflow(a:AuraAgentNetworkActor,input:{name:string;description?:string;mode?:'sequential'|'parallel';definition?:Record<string,unknown>}){owner(a);const [row]=await this.deps.db.insert(auraNetworkWorkflows).values({companyId:a.companyId,name:input.name,description:input.description??null,mode:input.mode??'sequential',definition:input.definition??{},createdByUserId:a.userId}).returning();await this.audit(a,'aura_agent_network.workflow.created',row.id,'workflow');return row;}
 async ensureExampleWorkflow(a:AuraAgentNetworkActor){owner(a);return this.createWorkflow(a,{name:'Finance to Executive communication draft',description:'Finance → Executive → Communication draft. No message is sent automatically.',definition:{flow:['finance','executive','communication_draft']}});}
 async startWorkflow(a:AuraAgentNetworkActor,workflowId:string){owner(a);const workflow=await this.deps.db.query.auraNetworkWorkflows.findFirst({where:and(eq(auraNetworkWorkflows.id,workflowId),eq(auraNetworkWorkflows.companyId,a.companyId))});if(!workflow)throw new AuraAgentNetworkError('NOT_FOUND','Workflow not found');const [run]=await this.deps.db.insert(auraNetworkWorkflowRuns).values({companyId:a.companyId,workflowId,status:'awaiting_approval',autoExecuted:false,requestedByUserId:a.userId}).returning();await this.createApproval(a,'workflow_start','aura_network_workflow_run',run.id);await this.audit(a,'aura_agent_network.workflow.start_requested',run.id,'workflow');return run;}
 async listRuns(a:AuraAgentNetworkActor){return this.deps.db.query.auraNetworkWorkflowRuns.findMany({where:eq(auraNetworkWorkflowRuns.companyId,a.companyId),orderBy:[desc(auraNetworkWorkflowRuns.createdAt)]});}
 async listTasks(a:AuraAgentNetworkActor,runId:string){return this.deps.db.query.auraNetworkWorkflowTasks.findMany({where:and(eq(auraNetworkWorkflowTasks.companyId,a.companyId),eq(auraNetworkWorkflowTasks.workflowRunId,runId)),orderBy:[desc(auraNetworkWorkflowTasks.createdAt)]});}
 async listApprovals(a:AuraAgentNetworkActor,history=false){return this.deps.db.query.auraNetworkApprovals.findMany({where:history?eq(auraNetworkApprovals.companyId,a.companyId):and(eq(auraNetworkApprovals.companyId,a.companyId),eq(auraNetworkApprovals.status,'awaiting_approval')),orderBy:[desc(auraNetworkApprovals.createdAt)]});}
 async decideApproval(a:AuraAgentNetworkActor,id:string,decision:'approve'|'reject',notes?:string){owner(a);const [row]=await this.deps.db.update(auraNetworkApprovals).set({status:decision==='approve'?'approved':'rejected',decidedByUserId:a.userId,decidedAt:new Date(),decisionNotes:notes??null,autoExecuted:false}).where(and(eq(auraNetworkApprovals.id,id),eq(auraNetworkApprovals.companyId,a.companyId))).returning();if(!row)throw new AuraAgentNetworkError('NOT_FOUND','Approval not found');await this.audit(a,`aura_agent_network.approval.${decision}`,id,'workflow');return {...row,autoExecuted:false as const,decidedAt:iso(row.decidedAt)};}
 async shareContext(a:AuraAgentNetworkActor,input:{fromAgentKey:AuraNetworkAgentKey;toAgentKey:AuraNetworkAgentKey;contextDomain:string}){owner(a);if(isForbiddenContextDomain(input.contextDomain)||!isAllowedContextDomain(input.contextDomain))throw new AuraAgentNetworkError('VALIDATION','Context domain is not permitted');const [row]=await this.deps.db.insert(auraNetworkContextAccessLogs).values({...input,companyId:a.companyId,accessGranted:false,requestedByUserId:a.userId}).returning();await this.createApproval(a,'context_share','aura_network_context_access_log',row.id);await this.audit(a,'aura_agent_network.context.share_requested',row.id);return row;}
 async listContext(a:AuraAgentNetworkActor){return this.deps.db.query.auraNetworkContextAccessLogs.findMany({where:eq(auraNetworkContextAccessLogs.companyId,a.companyId),orderBy:[desc(auraNetworkContextAccessLogs.createdAt)]});}
 async listActivity(a:AuraAgentNetworkActor){return this.deps.db.query.auraNetworkActivity.findMany({where:eq(auraNetworkActivity.companyId,a.companyId),orderBy:[desc(auraNetworkActivity.createdAt)],limit:100});}
 private async createApproval(a:AuraAgentNetworkActor,type:'handoff'|'workflow_start'|'context_share',entityType:string,entityId:string){await this.deps.db.insert(auraNetworkApprovals).values({companyId:a.companyId,type,entityType,entityId,status:'awaiting_approval',autoExecuted:false,requestedByUserId:a.userId});}
 private async count(a:AuraAgentNetworkActor,table:any){const [r]=await this.deps.db.select({count:sql<number>`count(*)::int`}).from(table).where(eq(table.companyId,a.companyId));return r?.count??0;}
}
