import { Router } from 'express';
import { z } from 'zod';
import type { EnterpriseBusinessEvolutionService } from '../services/enterprise-business-evolution.service.js';
import { EnterpriseBusinessEvolutionError } from '../services/enterprise-business-evolution.service.js';
import { createAuthMiddleware, type AuthenticatedRequest } from '../middleware/auth.js';
import { requireAnyPermission } from '../middleware/rbac.js';

const platformConfigSchema = z.object({
  learningGovernance: z.record(z.unknown()).optional(),
  experimentSafetyDefaults: z.record(z.unknown()).optional(),
  evaluationTemplates: z.record(z.unknown()).optional(),
  aggregationThresholds: z.record(z.unknown()).optional(),
  crossTenantPrivacyRules: z.record(z.unknown()).optional(),
  agentImprovementStandards: z.record(z.unknown()).optional(),
  autonomousAllowlist: z.record(z.unknown()).optional(),
  rollbackRequirements: z.record(z.unknown()).optional(),
  auditRetentionDays: z.number().int().min(1).optional(),
  recommendationThresholds: z.record(z.unknown()).optional(),
  learningScope: z.record(z.unknown()).optional(),
  dataSources: z.record(z.unknown()).optional(),
});
const observationSchema = z.object({ observationKey: z.string().trim().min(1).max(200), sourceModule: z.string().trim().max(100).optional(), observationType: z.string().trim().min(1).max(200), title: z.string().trim().min(1).max(200), description: z.string().trim().max(5000).optional(), sourceEntityType: z.string().trim().max(100).optional(), sourceEntityId: z.string().uuid().optional(), evidence: z.record(z.unknown()).optional(), config: z.record(z.unknown()).optional() });
const hypothesisSchema = z.object({ hypothesisKey: z.string().trim().min(1).max(200), title: z.string().trim().min(1).max(200), problemStatement: z.string().trim().max(5000).optional(), proposedChange: z.string().trim().max(5000).optional(), expectedOutcome: z.string().trim().max(5000).optional(), patternId: z.string().uuid().optional(), riskLevel: z.string().trim().max(50).optional(), measurementMethod: z.string().trim().max(5000).optional(), successCriteria: z.string().trim().max(5000).optional(), rollbackPlan: z.string().trim().max(5000).optional() });
const recommendationSchema = z.object({ recommendationKey: z.string().trim().min(1).max(200), category: z.string().trim().min(1).max(100), title: z.string().trim().min(1).max(200), description: z.string().trim().max(5000).optional(), expectedBenefit: z.string().trim().max(5000).optional(), expectedCost: z.string().trim().max(5000).optional(), riskLevel: z.string().trim().max(50).optional(), hypothesisId: z.string().uuid().optional(), approvalRequired: z.boolean().optional(), measurementPlan: z.string().trim().max(5000).optional(), rollbackPlan: z.string().trim().max(5000).optional() });
const experimentSchema = z.object({ experimentKey: z.string().trim().min(1).max(200), title: z.string().trim().min(1).max(200), description: z.string().trim().max(5000).optional(), experimentType: z.string().trim().min(1).max(200), riskLevel: z.string().trim().max(50).optional(), hypothesisId: z.string().uuid().optional(), recommendationId: z.string().uuid().optional(), safetyControls: z.record(z.unknown()).optional(), scheduledStartAt: z.string().trim().optional(), scheduledEndAt: z.string().trim().optional() });
const outcomeSchema = z.object({ title: z.string().trim().min(1).max(200), experimentId: z.string().uuid().optional(), recommendationId: z.string().uuid().optional(), baselineMetrics: z.record(z.unknown()).optional(), afterMetrics: z.record(z.unknown()).optional(), operationalImpact: z.string().trim().max(5000).optional(), financialImpactCents: z.number().int().optional(), customerImpact: z.string().trim().max(5000).optional(), workforceImpact: z.string().trim().max(5000).optional() });
const feedbackSchema = z.object({ targetType: z.string().trim().min(1).max(100), targetId: z.string().uuid(), feedbackRating: z.string().trim().min(1).max(100), feedbackText: z.string().trim().max(5000).optional(), metadata: z.record(z.unknown()).optional() });
const improvementSchema = z.object({ itemKey: z.string().trim().min(1).max(200), sourceType: z.string().trim().min(1).max(100), title: z.string().trim().min(1).max(200), description: z.string().trim().max(5000).optional(), priority: z.string().trim().max(50).optional(), expectedBenefit: z.string().trim().max(5000).optional(), evidence: z.record(z.unknown()).optional() });
const draftSchema = z.object({ draftType: z.string().trim().min(1).max(100), title: z.string().trim().min(1).max(200), content: z.string().trim().min(1), sourceRecords: z.record(z.unknown()).optional(), aiGenerated: z.boolean().optional() });
const safeOptimizationSchema = z.object({ optimizationKey: z.string().trim().min(1).max(100), input: z.record(z.unknown()).optional() });
const recommendationEventSchema = z.object({ eventType: z.string().trim().min(1).max(100), decisionReason: z.string().trim().max(5000).optional(), expectedOutcome: z.string().trim().max(5000).optional(), actualOutcome: z.string().trim().max(5000).optional(), lessonsLearned: z.string().trim().max(5000).optional() });

type RouterDeps = { enterpriseBusinessEvolutionService: EnterpriseBusinessEvolutionService; jwtSecret: string; authService: import('../services/auth.service.js').AuthService };
function getAuth(req: import('express').Request) { return (req as AuthenticatedRequest).auth; }
function getRouteParam(value: string | string[]) { return Array.isArray(value) ? value[0]! : value; }
function staffScope(req: import('express').Request) { const auth = getAuth(req); return { companyId: auth.companyId, userId: auth.userId }; }
function handleError(error: unknown, res: import('express').Response) { if (error instanceof EnterpriseBusinessEvolutionError) { const status = error.code === 'NOT_FOUND' ? 404 : error.code === 'VALIDATION_ERROR' || error.code === 'CONFLICT' ? 400 : 500; res.status(status).json({ error: { code: error.code, message: error.message } }); return; } throw error; }

export function createEnterpriseBusinessEvolutionRouter(deps: RouterDeps): Router {
  const router = Router();
  const requireStaffAuth = createAuthMiddleware({ jwtSecret: deps.jwtSecret, authService: deps.authService });
  const requireRead = requireAnyPermission('business_evolution:read', 'business_evolution:manage', 'intelligence:read');
  const requireWrite = requireAnyPermission('business_evolution:write', 'business_evolution:manage', 'intelligence:write');
  const requireManage = requireAnyPermission('business_evolution:manage', 'intelligence:write', 'platform:manage');

  router.get('/dashboard', requireStaffAuth, requireRead, async (req, res) => { try { const auth = getAuth(req); const dashboard = await deps.enterpriseBusinessEvolutionService.getDashboard(auth.companyId); res.json({ data: { dashboard } }); } catch (error) { handleError(error, res); } });
  router.get('/evolution-monitoring', requireStaffAuth, requireRead, async (req, res) => { try { const auth = getAuth(req); const evolutionMonitoring = await deps.enterpriseBusinessEvolutionService.getEvolutionMonitoring(auth.companyId); res.json({ data: { evolutionMonitoring } }); } catch (error) { handleError(error, res); } });
  router.get('/platform-config', requireStaffAuth, requireRead, async (req, res) => { try { const auth = getAuth(req); const platformConfig = await deps.enterpriseBusinessEvolutionService.getPlatformConfig(auth.companyId); res.json({ data: { platformConfig } }); } catch (error) { handleError(error, res); } });
  router.put('/platform-config', requireStaffAuth, requireManage, async (req, res) => { const parsed = platformConfigSchema.safeParse(req.body); if (!parsed.success) { res.status(400).json({ error: { code: 'VALIDATION_ERROR', message: 'Invalid platform config' } }); return; } try { const platformConfig = await deps.enterpriseBusinessEvolutionService.updatePlatformConfig(staffScope(req), parsed.data); res.json({ data: { platformConfig } }); } catch (error) { handleError(error, res); } });
  router.post('/observations/sync', requireStaffAuth, requireWrite, async (req, res) => { try { const observations = await deps.enterpriseBusinessEvolutionService.syncObservations(staffScope(req)); res.json({ data: { observations } }); } catch (error) { handleError(error, res); } });
  router.post('/patterns/detect', requireStaffAuth, requireWrite, async (req, res) => { try { const patterns = await deps.enterpriseBusinessEvolutionService.detectPatterns(staffScope(req)); res.json({ data: { patterns } }); } catch (error) { handleError(error, res); } });
  router.post('/evolution-alerts/sync', requireStaffAuth, requireWrite, async (req, res) => { try { const evolutionAlerts = await deps.enterpriseBusinessEvolutionService.syncEvolutionAlerts(staffScope(req)); res.json({ data: { evolutionAlerts } }); } catch (error) { handleError(error, res); } });
  router.post('/analytics/capture', requireStaffAuth, requireWrite, async (req, res) => { try { const analytics = await deps.enterpriseBusinessEvolutionService.captureAnalytics(staffScope(req)); res.json({ data: { analytics } }); } catch (error) { handleError(error, res); } });
  router.post('/agent-performance/capture', requireStaffAuth, requireWrite, async (req, res) => { try { const snapshots = await deps.enterpriseBusinessEvolutionService.captureAgentPerformance(staffScope(req)); res.json({ data: { snapshots } }); } catch (error) { handleError(error, res); } });
  router.post('/process-mining/sync', requireStaffAuth, requireWrite, async (req, res) => { try { const results = await deps.enterpriseBusinessEvolutionService.syncProcessMining(staffScope(req)); res.json({ data: { results } }); } catch (error) { handleError(error, res); } });
  router.post('/safe-optimizations/execute', requireStaffAuth, requireManage, async (req, res) => { const parsed = safeOptimizationSchema.safeParse(req.body); if (!parsed.success) { res.status(400).json({ error: { code: 'VALIDATION_ERROR', message: 'Invalid safe optimization request' } }); return; } try { const result = await deps.enterpriseBusinessEvolutionService.executeSafeOptimization(staffScope(req), parsed.data); res.json({ data: { result } }); } catch (error) { handleError(error, res); } });
  router.get('/aura-context', requireStaffAuth, requireRead, async (req, res) => { try { const auth = getAuth(req); const auraContext = await deps.enterpriseBusinessEvolutionService.buildAuraContext(auth.companyId); res.json({ data: { auraContext } }); } catch (error) { handleError(error, res); } });
  router.get('/observations', requireStaffAuth, requireRead, async (req, res) => { try { const auth = getAuth(req); const observations = await deps.enterpriseBusinessEvolutionService.listObservations(auth.companyId); res.json({ data: { observations } }); } catch (error) { handleError(error, res); } });
  router.post('/observations', requireStaffAuth, requireWrite, async (req, res) => { const parsed = observationSchema.safeParse(req.body); if (!parsed.success) { res.status(400).json({ error: { code: 'VALIDATION_ERROR', message: 'Invalid observation' } }); return; } try { const observation = await deps.enterpriseBusinessEvolutionService.createObservation(staffScope(req), parsed.data); res.status(201).json({ data: { observation } }); } catch (error) { handleError(error, res); } });
  router.get('/patterns', requireStaffAuth, requireRead, async (req, res) => { try { const auth = getAuth(req); const patterns = await deps.enterpriseBusinessEvolutionService.listPatterns(auth.companyId); res.json({ data: { patterns } }); } catch (error) { handleError(error, res); } });
  router.get('/hypotheses', requireStaffAuth, requireRead, async (req, res) => { try { const auth = getAuth(req); const hypotheses = await deps.enterpriseBusinessEvolutionService.listHypotheses(auth.companyId); res.json({ data: { hypotheses } }); } catch (error) { handleError(error, res); } });
  router.post('/hypotheses', requireStaffAuth, requireWrite, async (req, res) => { const parsed = hypothesisSchema.safeParse(req.body); if (!parsed.success) { res.status(400).json({ error: { code: 'VALIDATION_ERROR', message: 'Invalid hypothesis' } }); return; } try { const hypothesis = await deps.enterpriseBusinessEvolutionService.createHypothesis(staffScope(req), parsed.data); res.status(201).json({ data: { hypothesis } }); } catch (error) { handleError(error, res); } });
  router.get('/recommendations', requireStaffAuth, requireRead, async (req, res) => { try { const auth = getAuth(req); const recommendations = await deps.enterpriseBusinessEvolutionService.listRecommendations(auth.companyId); res.json({ data: { recommendations } }); } catch (error) { handleError(error, res); } });
  router.post('/recommendations', requireStaffAuth, requireWrite, async (req, res) => { const parsed = recommendationSchema.safeParse(req.body); if (!parsed.success) { res.status(400).json({ error: { code: 'VALIDATION_ERROR', message: 'Invalid recommendation' } }); return; } try { const recommendation = await deps.enterpriseBusinessEvolutionService.createRecommendation(staffScope(req), parsed.data); res.status(201).json({ data: { recommendation } }); } catch (error) { handleError(error, res); } });
  router.patch('/recommendations/:recommendationId', requireStaffAuth, requireWrite, async (req, res) => { const parsed = recommendationSchema.partial().extend({ workflowStatus: z.string().optional() }).safeParse(req.body); if (!parsed.success) { res.status(400).json({ error: { code: 'VALIDATION_ERROR', message: 'Invalid recommendation update' } }); return; } try { const recommendation = await deps.enterpriseBusinessEvolutionService.updateRecommendation(staffScope(req), getRouteParam(req.params.recommendationId), parsed.data); res.json({ data: { recommendation } }); } catch (error) { handleError(error, res); } });
  router.post('/recommendations/:recommendationId/events', requireStaffAuth, requireWrite, async (req, res) => { const parsed = recommendationEventSchema.safeParse(req.body); if (!parsed.success) { res.status(400).json({ error: { code: 'VALIDATION_ERROR', message: 'Invalid recommendation event' } }); return; } try { const event = await deps.enterpriseBusinessEvolutionService.recordRecommendationEvent(staffScope(req), getRouteParam(req.params.recommendationId), parsed.data.eventType, parsed.data); res.status(201).json({ data: { event } }); } catch (error) { handleError(error, res); } });
  router.get('/experiments', requireStaffAuth, requireRead, async (req, res) => { try { const auth = getAuth(req); const experiments = await deps.enterpriseBusinessEvolutionService.listExperiments(auth.companyId); res.json({ data: { experiments } }); } catch (error) { handleError(error, res); } });
  router.post('/experiments', requireStaffAuth, requireWrite, async (req, res) => { const parsed = experimentSchema.safeParse(req.body); if (!parsed.success) { res.status(400).json({ error: { code: 'VALIDATION_ERROR', message: 'Invalid experiment' } }); return; } try { const experiment = await deps.enterpriseBusinessEvolutionService.createExperiment(staffScope(req), parsed.data); res.status(201).json({ data: { experiment } }); } catch (error) { handleError(error, res); } });
  router.patch('/experiments/:experimentId', requireStaffAuth, requireWrite, async (req, res) => { const parsed = experimentSchema.partial().extend({ workflowStatus: z.string().optional() }).safeParse(req.body); if (!parsed.success) { res.status(400).json({ error: { code: 'VALIDATION_ERROR', message: 'Invalid experiment update' } }); return; } try { const experiment = await deps.enterpriseBusinessEvolutionService.updateExperiment(staffScope(req), getRouteParam(req.params.experimentId), parsed.data); res.json({ data: { experiment } }); } catch (error) { handleError(error, res); } });
  router.get('/outcomes', requireStaffAuth, requireRead, async (req, res) => { try { const auth = getAuth(req); const outcomes = await deps.enterpriseBusinessEvolutionService.listOutcomes(auth.companyId); res.json({ data: { outcomes } }); } catch (error) { handleError(error, res); } });
  router.post('/outcomes', requireStaffAuth, requireWrite, async (req, res) => { const parsed = outcomeSchema.safeParse(req.body); if (!parsed.success) { res.status(400).json({ error: { code: 'VALIDATION_ERROR', message: 'Invalid outcome' } }); return; } try { const outcome = await deps.enterpriseBusinessEvolutionService.createOutcome(staffScope(req), parsed.data); res.status(201).json({ data: { outcome } }); } catch (error) { handleError(error, res); } });
  router.get('/continuous-improvement-items', requireStaffAuth, requireRead, async (req, res) => { try { const auth = getAuth(req); const items = await deps.enterpriseBusinessEvolutionService.listContinuousImprovementItems(auth.companyId); res.json({ data: { items } }); } catch (error) { handleError(error, res); } });
  router.post('/continuous-improvement-items', requireStaffAuth, requireWrite, async (req, res) => { const parsed = improvementSchema.safeParse(req.body); if (!parsed.success) { res.status(400).json({ error: { code: 'VALIDATION_ERROR', message: 'Invalid improvement item' } }); return; } try { const item = await deps.enterpriseBusinessEvolutionService.createContinuousImprovementItem(staffScope(req), parsed.data); res.status(201).json({ data: { item } }); } catch (error) { handleError(error, res); } });
  router.get('/strategic-roadmap-items', requireStaffAuth, requireRead, async (req, res) => { try { const auth = getAuth(req); const items = await deps.enterpriseBusinessEvolutionService.listStrategicRoadmapItems(auth.companyId); res.json({ data: { items } }); } catch (error) { handleError(error, res); } });
  router.get('/maturity-assessments', requireStaffAuth, requireRead, async (req, res) => { try { const auth = getAuth(req); const assessments = await deps.enterpriseBusinessEvolutionService.listMaturityAssessments(auth.companyId); res.json({ data: { assessments } }); } catch (error) { handleError(error, res); } });
  router.get('/agent-performance-snapshots', requireStaffAuth, requireRead, async (req, res) => { try { const auth = getAuth(req); const snapshots = await deps.enterpriseBusinessEvolutionService.listAgentPerformanceSnapshots(auth.companyId); res.json({ data: { snapshots } }); } catch (error) { handleError(error, res); } });
  router.get('/agent-improvements', requireStaffAuth, requireRead, async (req, res) => { try { const auth = getAuth(req); const improvements = await deps.enterpriseBusinessEvolutionService.listAgentImprovements(auth.companyId); res.json({ data: { improvements } }); } catch (error) { handleError(error, res); } });
  router.get('/prompt-policy-versions', requireStaffAuth, requireRead, async (req, res) => { try { const auth = getAuth(req); const versions = await deps.enterpriseBusinessEvolutionService.listPromptPolicyVersions(auth.companyId); res.json({ data: { versions } }); } catch (error) { handleError(error, res); } });
  router.get('/ai-evaluations', requireStaffAuth, requireRead, async (req, res) => { try { const auth = getAuth(req); const evaluations = await deps.enterpriseBusinessEvolutionService.listAiEvaluations(auth.companyId); res.json({ data: { evaluations } }); } catch (error) { handleError(error, res); } });
  router.get('/knowledge-reinforcements', requireStaffAuth, requireRead, async (req, res) => { try { const auth = getAuth(req); const reinforcements = await deps.enterpriseBusinessEvolutionService.listKnowledgeReinforcements(auth.companyId); res.json({ data: { reinforcements } }); } catch (error) { handleError(error, res); } });
  router.get('/process-mining-results', requireStaffAuth, requireRead, async (req, res) => { try { const auth = getAuth(req); const results = await deps.enterpriseBusinessEvolutionService.listProcessMiningResults(auth.companyId); res.json({ data: { results } }); } catch (error) { handleError(error, res); } });
  router.get('/evolution-alerts', requireStaffAuth, requireRead, async (req, res) => { try { const auth = getAuth(req); const evolutionAlerts = await deps.enterpriseBusinessEvolutionService.listEvolutionAlerts(auth.companyId); res.json({ data: { evolutionAlerts } }); } catch (error) { handleError(error, res); } });
  router.post('/evolution-alerts/:alertId/acknowledge', requireStaffAuth, requireWrite, async (req, res) => { try { const evolutionAlert = await deps.enterpriseBusinessEvolutionService.acknowledgeEvolutionAlert(staffScope(req), getRouteParam(req.params.alertId)); res.json({ data: { evolutionAlert } }); } catch (error) { handleError(error, res); } });
  router.post('/user-feedback', requireStaffAuth, requireWrite, async (req, res) => { const parsed = feedbackSchema.safeParse(req.body); if (!parsed.success) { res.status(400).json({ error: { code: 'VALIDATION_ERROR', message: 'Invalid feedback' } }); return; } try { const feedback = await deps.enterpriseBusinessEvolutionService.createUserFeedback(staffScope(req), parsed.data); res.status(201).json({ data: { feedback } }); } catch (error) { handleError(error, res); } });
  router.get('/user-feedback', requireStaffAuth, requireRead, async (req, res) => { try { const auth = getAuth(req); const feedback = await deps.enterpriseBusinessEvolutionService.listUserFeedback(auth.companyId); res.json({ data: { feedback } }); } catch (error) { handleError(error, res); } });
  router.post('/action-drafts', requireStaffAuth, requireWrite, async (req, res) => { const parsed = draftSchema.safeParse(req.body); if (!parsed.success) { res.status(400).json({ error: { code: 'VALIDATION_ERROR', message: 'Invalid action draft' } }); return; } try { const actionDraft = await deps.enterpriseBusinessEvolutionService.createActionDraft(staffScope(req), parsed.data); res.status(201).json({ data: { actionDraft } }); } catch (error) { handleError(error, res); } });
  router.get('/audit-logs', requireStaffAuth, requireRead, async (req, res) => { try { const auth = getAuth(req); const auditLogs = await deps.enterpriseBusinessEvolutionService.listAuditLogs(auth.companyId); res.json({ data: { auditLogs } }); } catch (error) { handleError(error, res); } });
  return router;
}
