export type AgentKey =
  | 'executive'
  | 'operations'
  | 'finance'
  | 'recruiting'
  | 'sales'
  | 'marketing'
  | 'lead_generation'
  | 'voice_receptionist'
  | 'customer_support'
  | 'procurement'
  | 'security'
  | 'integration'
  | 'business_intelligence'
  | 'automation';

export type AgentProfileStatus = 'draft' | 'active' | 'paused';

export type AgentExecutionStatus = 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';

export type AgentExecutionMode = 'manual' | 'preview';

export const AGENT_PROFILE_STATUS_OPTIONS: Array<{ value: AgentProfileStatus; label: string }> = [
  { value: 'draft', label: 'Draft' },
  { value: 'active', label: 'Active' },
  { value: 'paused', label: 'Paused' },
];

export const AGENT_EXECUTION_STATUS_OPTIONS: Array<{ value: AgentExecutionStatus; label: string }> =
  [
    { value: 'pending', label: 'Pending' },
    { value: 'running', label: 'Running' },
    { value: 'completed', label: 'Completed' },
    { value: 'failed', label: 'Failed' },
    { value: 'cancelled', label: 'Cancelled' },
  ];

export type AgentRegistryEntry = {
  agentKey: AgentKey;
  name: string;
  description: string;
  focusAreas: string[];
  suggestedPermissions: string[];
  suggestedToolKeys: string[];
  foundationOnly?: boolean;
};

export type AgentToolDefinition = {
  toolKey: string;
  name: string;
  description: string;
  category: string;
  requiredPermissions: string[];
  executable: boolean;
  requiresApproval?: boolean;
};

export const AGENT_REGISTRY: AgentRegistryEntry[] = [
  {
    agentKey: 'executive',
    name: 'Executive Command Agent',
    description:
      'Executive command centre — business health analysis, strategic recommendations, risk detection, growth opportunities, and performance overview across finance, operations, sales, workforce, and procurement. No autonomous business decisions.',
    focusAreas: [
      'Business health analysis',
      'Strategic recommendations',
      'Risk detection',
      'Growth opportunities',
      'Performance overview',
    ],
    suggestedPermissions: [
      'executive:read',
      'executive:write',
      'customers:read',
      'jobs:read',
      'finance:read',
      'fleet:read',
      'inventory:read',
      'procurement:read',
      'workforce:read',
      'sales:read',
      'marketing:read',
      'intelligence:read',
      'analytics:read',
      'quality:read',
      'bi:read',
      'integrations:read',
      'ai_orchestration:read',
      'ai_orchestration:write',
    ],
    suggestedToolKeys: [
      'read_business_health',
      'read_executive_alerts',
      'read_business_summary',
      'read_strategic_recommendations',
      'read_intelligence_dashboard',
      'read_analytics_dashboard',
      'read_analytics_profitability',
      'read_customer_analytics',
      'read_business_kpis',
      'read_business_dashboard',
      'read_business_reports',
      'read_business_insights',
      'read_predictive_forecasts',
      'read_procurement_context',
      'read_workforce_context',
      'read_sales_context',
      'read_comeback_history',
      'read_quality_score',
      'read_root_cause_analysis',
      'read_warranty_history',
      'read_supplier_quality',
      'draft_quality_action',
      'draft_quality_review',
      'draft_payroll_recommendation',
      'read_recommendations',
      'read_memory',
      'read_orchestration_status',
      'read_ai_provider_status',
      'read_ai_capabilities',
      'read_ai_costs',
      'read_ai_quality',
      'read_ai_routing',
      'read_prompt_versions',
      'draft_prompt_update',
      'draft_provider_configuration',
      'draft_executive_action',
      'draft_business_report',
      'summarize_context',
    ],
  },
  {
    agentKey: 'operations',
    name: 'Operations Agent',
    description:
      'Operations intelligence for dispatch, technician workload, schedule conflicts, job priorities, fleet availability, and GPS-aware coordination.',
    focusAreas: [
      'Technician workload analysis',
      'Schedule conflict detection',
      'Job priority recommendations',
      'Fleet availability checks',
    ],
    suggestedPermissions: ['jobs:read', 'dispatch:read', 'fleet:read', 'inventory:read', 'asset_equipment:read', 'dispatch_intelligence:read', 'fleet_intelligence:read', 'voice:read', 'automation:read', 'intelligence:read', 'analytics:read', 'knowledge:read'],
    suggestedToolKeys: [
      'read_jobs',
      'read_inventory',
      'read_fleet',
      'read_gps_positions',
      'read_asset_register',
      'read_asset_history',
      'read_maintenance_schedule',
      'read_asset_performance',
      'read_inspection_history',
      'read_calibration_status',
      'draft_maintenance_action',
      'draft_asset_replacement',
      'read_intelligence_dashboard',
      'read_technician_performance',
      'read_analytics_dashboard',
      'read_mobile_context',
      'read_mobile_dashboard',
      'read_mobile_jobs',
      'read_mobile_route',
      'read_mobile_inventory',
      'read_mobile_notifications',
      'draft_mobile_request',
      'read_comeback_history',
      'read_quality_score',
      'read_root_cause_analysis',
      'read_warranty_history',
      'read_supplier_quality',
      'draft_quality_action',
      'draft_quality_review',
      'read_orchestration_status',
      'read_dispatch_dashboard',
      'read_call_queue',
      'read_technician_matching',
      'read_dispatch_recommendations',
      'read_callback_queue',
      'read_emergency_dispatch',
      'draft_dispatch_action',
      'draft_callback_action',
      'read_fleet_dashboard',
      'read_trip_history',
      'read_monthly_trip_report',
      'read_driver_behaviour',
      'read_vehicle_utilization',
      'read_fleet_costs',
      'draft_fleet_action',
      'draft_vehicle_replacement',
      'read_recommendations',
      'read_workflows',
      'read_workflow_history',
      'validate_workflow',
      'simulate_workflow',
      'read_knowledge_base',
      'search_knowledge',
      'read_sop',
      'draft_workflow',
      'summarize_context',
    ],
  },
  {
    agentKey: 'finance',
    name: 'Finance Controller Agent',
    description:
      'AI Finance Controller — cash flow intelligence, profitability analysis, receivables tracking, expense analysis, budget variance, financial forecasting, risk detection, and executive finance recommendations. Uses invoices, payments, Xero, jobs, and procurement data only. Never modifies financial records without approval.',
    focusAreas: [
      'Cash flow intelligence',
      'Profitability analysis',
      'Accounts receivable intelligence',
      'Expense analysis',
      'Budget intelligence',
      'Financial forecasting',
      'Financial risk detection',
      'Finance recommendations',
    ],
    suggestedPermissions: ['finance:read', 'finance:write', 'customers:read', 'intelligence:read', 'analytics:read', 'integrations:read', 'procurement:read'],
    suggestedToolKeys: [
      'read_invoices',
      'read_quotes',
      'read_payments',
      'read_recommendations',
      'analyze_cash_flow',
      'read_analytics_dashboard',
      'read_analytics_profitability',
      'read_cashflow_context',
      'read_profitability_context',
      'read_receivables_context',
      'read_expense_context',
      'read_budget_context',
      'read_finance_forecast',
      'read_integrations',
      'read_api_health',
      'read_sync_status',
      'read_webhook_status',
      'validate_integration',
      'draft_integration_action',
      'draft_finance_action',
      'summarize_context',
    ],
  },
  {
    agentKey: 'recruiting',
    name: 'Workforce Intelligence Agent',
    description:
      'Workforce intelligence — hiring pipeline analysis, staffing recommendations, skills gaps, technician performance insights, training recommendations, and capacity planning. No automatic hiring or employment decisions.',
    focusAreas: [
      'Workforce analysis',
      'Staffing recommendations',
      'Recruitment insights',
      'Skills analysis',
      'Training recommendations',
      'Capacity planning',
    ],
    suggestedPermissions: [
      'recruiting:read',
      'recruiting:write',
      'workforce:read',
      'workforce:write',
      'analytics:read',
      'intelligence:read',
      'knowledge:read',
    ],
    suggestedToolKeys: [
      'read_workforce_context',
      'read_candidate_pipeline',
      'read_candidates',
      'read_skill_gaps',
      'read_staffing_insights',
      'read_technician_performance',
      'score_candidates',
      'create_candidate',
      'update_candidate_status',
      'draft_job_ad',
      'draft_interview_questions',
      'draft_hiring_recommendation',
      'draft_recruitment_action',
      'draft_candidate_communication',
      'draft_interview_request',
      'draft_training_plan',
      'read_knowledge_base',
      'search_knowledge',
      'read_sop',
      'read_training',
      'draft_knowledge_article',
      'summarize_context',
    ],
  },
  {
    agentKey: 'sales',
    name: 'Sales Agent',
    description:
      'Sales intelligence for opportunity analysis, follow-up recommendations, quote assistance, pipeline insights, and revenue growth. Never sends messages or modifies records without approval.',
    focusAreas: [
      'Opportunity analysis',
      'Follow-up recommendations',
      'Quote assistance',
      'Pipeline tracking',
      'Sales performance insights',
    ],
    suggestedPermissions: [
      'sales:read',
      'sales:write',
      'customers:read',
      'finance:read',
      'communications:read',
      'analytics:read',
      'intelligence:read',
    ],
    suggestedToolKeys: [
      'read_sales_context',
      'read_opportunities',
      'read_sales_pipeline',
      'read_customers',
      'read_quotes',
      'read_customer_analytics',
      'read_recommendations',
      'draft_sales_follow_up',
      'draft_quote_recommendation',
      'create_customer_note',
      'send_whatsapp_draft',
      'summarize_context',
    ],
  },
  {
    agentKey: 'marketing',
    name: 'Marketing Agent',
    description:
      'Marketing intelligence for customer segmentation, campaign recommendations, engagement analysis, and content guidance. Never publishes or sends communications without approval.',
    focusAreas: [
      'Customer segmentation',
      'Campaign recommendations',
      'Engagement analysis',
      'Content intelligence',
      'Retention opportunities',
    ],
    suggestedPermissions: [
      'marketing:read',
      'marketing:write',
      'customers:read',
      'communications:read',
      'analytics:read',
      'sales:read',
      'intelligence:read',
    ],
    suggestedToolKeys: [
      'read_marketing_context',
      'read_customer_segments',
      'read_marketing_activity',
      'read_customers',
      'read_customer_analytics',
      'read_recommendations',
      'draft_marketing_campaign',
      'draft_marketing_content',
      'send_whatsapp_draft',
      'create_customer_note',
      'summarize_context',
    ],
  },
  {
    agentKey: 'lead_generation',
    name: 'Lead Generation Agent',
    description:
      'Lead generation and acquisition intelligence for identifying, scoring, and qualifying business opportunities. Recommends follow-ups and sales handoffs using real CRM, communication, and job data. Never contacts leads or creates opportunities without approval.',
    focusAreas: [
      'Lead identification',
      'Lead scoring',
      'Acquisition insights',
      'Qualification support',
      'Sales handoff recommendations',
    ],
    suggestedPermissions: [
      'leads:read',
      'leads:write',
      'customers:read',
      'sales:read',
      'communications:read',
      'analytics:read',
      'intelligence:read',
    ],
    suggestedToolKeys: [
      'read_lead_context',
      'read_lead_pipeline',
      'score_lead',
      'read_acquisition_insights',
      'read_customers',
      'read_opportunities',
      'read_sales_pipeline',
      'read_recommendations',
      'draft_lead_follow_up',
      'draft_lead_handoff',
      'create_customer_note',
      'summarize_context',
    ],
  },
  {
    agentKey: 'voice_receptionist',
    name: 'Voice Receptionist Agent',
    description:
      'Voice AI receptionist for customer enquiries, qualification, appointment assistance, and follow-up drafts. Uses real call sessions, CRM, scheduling, and job data. Never makes calls or executes customer actions without approval.',
    focusAreas: [
      'Customer enquiry handling',
      'Call qualification',
      'Appointment assistance',
      'Follow-up recommendations',
      'Voice session intelligence',
    ],
    suggestedPermissions: [
      'voice:read',
      'voice:write',
      'customers:read',
      'communications:read',
      'jobs:read',
      'dispatch:read',
      'sales:read',
      'leads:read',
      'communications_intelligence:read',
      'personal_communications:read',
      'intelligence:read',
    ],
    suggestedToolKeys: [
      'read_voice_context',
      'read_call_history',
      'read_conversation_summary',
      'read_customer_communications',
      'read_whatsapp_history',
      'read_personal_communications_dashboard',
      'read_business_conversations',
      'read_voice_note_summary',
      'read_media_analysis',
      'read_follow_up_queue',
      'read_communication_classification',
      'draft_business_action',
      'read_email_threads',
      'read_sms_history',
      'summarize_call',
      'read_acquisition_insights',
      'read_customers',
      'read_jobs',
      'read_sales_context',
      'read_lead_context',
      'draft_follow_up_from_call',
      'draft_appointment_request_from_call',
      'draft_lead_from_call',
      'draft_customer_note_from_call',
      'draft_customer_reply',
      'draft_follow_up',
      'create_customer_note',
      'summarize_context',
    ],
  },
  {
    agentKey: 'customer_support',
    name: 'Customer Support Agent',
    description:
      'AI customer support for answering questions, providing job updates, explaining invoices, and drafting responses. Uses authorised customer, job, finance, and portal data only. Never sends messages, makes promises, or changes records without approval.',
    focusAreas: [
      'Customer question handling',
      'Job status assistance',
      'Invoice and quote explanations',
      'Support escalation',
      'Draft response recommendations',
    ],
    suggestedPermissions: [
      'customer_support:read',
      'customer_support:write',
      'customers:read',
      'jobs:read',
      'finance:read',
      'documents:read',
      'communications:read',
      'portal:read',
      'voice:read',
      'communications_intelligence:read',
      'personal_communications:read',
      'intelligence:read',
      'knowledge:read',
    ],
    suggestedToolKeys: [
      'read_customer_support_context',
      'read_customer_conversation',
      'read_customer_communications',
      'read_conversation_summary',
      'read_whatsapp_history',
      'read_personal_communications_dashboard',
      'read_business_conversations',
      'read_follow_up_queue',
      'read_communication_classification',
      'draft_business_action',
      'read_email_threads',
      'read_sms_history',
      'read_call_history',
      'read_customer_job_status',
      'read_customer_dashboard',
      'read_customer_jobs',
      'read_customer_finances',
      'read_customer_notifications',
      'search_customer_knowledge',
      'draft_customer_request',
      'read_customers',
      'read_jobs',
      'read_invoices',
      'read_quotes',
      'read_voice_context',
      'draft_customer_response',
      'draft_customer_reply',
      'draft_follow_up',
      'draft_appointment_update',
      'draft_invoice_explanation',
      'draft_service_information_response',
      'read_knowledge_base',
      'search_knowledge',
      'read_sop',
      'read_company_policy',
      'create_customer_note',
      'summarize_context',
    ],
  },
  {
    agentKey: 'procurement',
    name: 'Procurement Intelligence Agent',
    description:
      'Procurement and inventory intelligence — stock analysis, purchasing recommendations, supplier insights, inventory risk detection, and cost intelligence. Never places orders or modifies stock without approval.',
    focusAreas: [
      'Stock analysis',
      'Purchasing recommendations',
      'Supplier insights',
      'Inventory risk detection',
      'Cost intelligence',
    ],
    suggestedPermissions: [
      'procurement:read',
      'procurement:write',
      'inventory:read',
      'finance:read',
      'jobs:read',
      'analytics:read',
      'intelligence:read',
    ],
    suggestedToolKeys: [
      'read_procurement_context',
      'read_stock_intelligence',
      'read_supplier_insights',
      'read_purchase_orders',
      'read_inventory',
      'draft_purchase_order',
      'summarize_context',
    ],
  },
  {
    agentKey: 'security',
    name: 'AURA Security Agent',
    description:
      'Enterprise security monitoring — security health, anomaly detection, permission review, audit log analysis, integration security, and AI usage monitoring. Recommendations only; never autonomously locks users, deletes data, removes permissions, or disables integrations.',
    focusAreas: [
      'Security health monitoring',
      'Anomaly detection',
      'Permission review',
      'Audit log review',
      'Integration security',
      'AI security monitoring',
      'Compliance readiness',
    ],
    suggestedPermissions: [
      'security:read',
      'security:write',
      'settings:manage',
      'integrations:read',
      'agents:read',
      'orchestration:read',
    ],
    suggestedToolKeys: [
      'read_security_dashboard',
      'read_audit_logs',
      'read_active_sessions',
      'read_risk_alerts',
      'read_login_events',
      'draft_security_action',
      'summarize_context',
    ],
  },
  {
    agentKey: 'integration',
    name: 'AURA Integration Agent',
    description:
      'Enterprise integration specialist — monitors connected services, detects failures, analyzes sync issues, and drafts integration repairs. Recommendations only; never autonomously reconnects, changes credentials, or performs destructive actions.',
    focusAreas: [
      'Integration health monitoring',
      'Failure detection',
      'Sync issue analysis',
      'Reconnect recommendations',
      'Integration health reports',
      'Connector diagnostics',
    ],
    suggestedPermissions: [
      'integrations:read',
      'integrations:manage',
      'agents:read',
      'orchestration:read',
    ],
    suggestedToolKeys: [
      'read_integration_platform_dashboard',
      'read_integration_connectors',
      'read_integrations',
      'read_api_health',
      'read_sync_status',
      'read_webhook_status',
      'validate_integration',
      'draft_integration_repair',
      'summarize_context',
    ],
  },
  {
    agentKey: 'business_intelligence',
    name: 'AURA Business Intelligence Agent',
    description:
      'Enterprise analytics specialist — analyzes company performance, explains KPI trends, detects anomalies, and drafts strategic reports from real tenant data. Recommendations only; never makes autonomous business decisions.',
    focusAreas: [
      'Company performance analysis',
      'Executive reporting',
      'Trend explanation',
      'Opportunity identification',
      'KPI anomaly detection',
      'Strategic report drafting',
    ],
    suggestedPermissions: [
      'bi:read',
      'bi:write',
      'analytics:read',
      'intelligence:read',
      'agents:read',
    ],
    suggestedToolKeys: [
      'read_enterprise_analytics_dashboard',
      'read_business_kpis',
      'read_business_insights',
      'read_predictive_forecasts',
      'read_data_warehouse',
      'read_analytics_governance',
      'read_analytics_dashboard',
      'draft_strategic_report',
      'draft_business_report',
      'summarize_context',
    ],
  },
  {
    agentKey: 'automation',
    name: 'AURA Automation Agent',
    description:
      'Enterprise automation specialist — analyzes workflows, detects bottlenecks, recommends automations, and drafts workflow improvements from real execution data. Recommendations only; never autonomously publishes or executes workflows.',
    focusAreas: [
      'Workflow analysis',
      'Automation recommendations',
      'Bottleneck detection',
      'Execution history review',
      'Workflow improvement drafting',
      'Automation health reporting',
    ],
    suggestedPermissions: [
      'automation:read',
      'automation:write',
      'agents:read',
      'orchestration:read',
    ],
    suggestedToolKeys: [
      'read_automation_studio_dashboard',
      'read_workflows',
      'read_workflow_history',
      'read_automation_monitoring',
      'validate_workflow',
      'simulate_workflow',
      'draft_workflow_improvement',
      'draft_workflow',
      'summarize_context',
    ],
  },
];

export const AGENT_TOOL_REGISTRY: AgentToolDefinition[] = [
  {
    toolKey: 'read_customers',
    name: 'Read customers',
    description: 'Read customer records and CRM context for an agent run.',
    category: 'crm',
    requiredPermissions: ['customers:read'],
    executable: true,
  },
  {
    toolKey: 'create_customer_note',
    name: 'Create customer note',
    description: 'Draft a CRM activity note for a customer (requires approval).',
    category: 'crm',
    requiredPermissions: ['customers:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'read_jobs',
    name: 'Read jobs',
    description: 'Read job records and scheduling context for an agent run.',
    category: 'operations',
    requiredPermissions: ['jobs:read'],
    executable: true,
  },
  {
    toolKey: 'update_job_status',
    name: 'Update job status',
    description: 'Propose a job status change (requires approval).',
    category: 'operations',
    requiredPermissions: ['jobs:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'read_invoices',
    name: 'Read invoices',
    description: 'Read invoice records and payment status for an agent run.',
    category: 'finance',
    requiredPermissions: ['finance:read'],
    executable: true,
  },
  {
    toolKey: 'read_quotes',
    name: 'Read quotes',
    description: 'Read quote records for an agent run.',
    category: 'finance',
    requiredPermissions: ['finance:read'],
    executable: true,
  },
  {
    toolKey: 'read_payments',
    name: 'Read payments',
    description: 'Read payment records for an agent run.',
    category: 'finance',
    requiredPermissions: ['finance:read'],
    executable: true,
  },
  {
    toolKey: 'read_inventory',
    name: 'Read inventory',
    description: 'Read inventory items and stock levels for an agent run.',
    category: 'operations',
    requiredPermissions: ['inventory:read'],
    executable: true,
  },
  {
    toolKey: 'read_fleet',
    name: 'Read fleet',
    description: 'Read vehicle and fleet context for an agent run.',
    category: 'operations',
    requiredPermissions: ['fleet:read'],
    executable: true,
  },
  {
    toolKey: 'read_gps_positions',
    name: 'Read GPS positions',
    description: 'Read latest Cartrack GPS positions for mapped fleet vehicles.',
    category: 'operations',
    requiredPermissions: ['fleet:read', 'integrations:read'],
    executable: true,
  },
  {
    toolKey: 'read_candidates',
    name: 'Read candidates',
    description: 'Read recruiting candidates and applications.',
    category: 'recruiting',
    requiredPermissions: ['recruiting:read'],
    executable: true,
  },
  {
    toolKey: 'create_candidate',
    name: 'Create candidate',
    description: 'Create a recruiting candidate profile (requires approval).',
    category: 'recruiting',
    requiredPermissions: ['recruiting:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'update_candidate_status',
    name: 'Update candidate status',
    description: 'Propose a candidate status change (requires approval).',
    category: 'recruiting',
    requiredPermissions: ['recruiting:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'send_whatsapp_draft',
    name: 'Send WhatsApp draft',
    description: 'Create a WhatsApp message draft for customer approval.',
    category: 'communications',
    requiredPermissions: ['communications:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'draft_job_ad',
    name: 'Draft job advert',
    description: 'Draft a job advert for review (requires approval to save).',
    category: 'recruiting',
    requiredPermissions: ['recruiting:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'draft_interview_questions',
    name: 'Draft interview questions',
    description: 'Draft interview questions for a role (requires approval to save).',
    category: 'recruiting',
    requiredPermissions: ['recruiting:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'summarize_context',
    name: 'Summarize context',
    description: 'Prepare a structured summary from permitted business context.',
    category: 'core',
    requiredPermissions: [],
    executable: true,
  },
  {
    toolKey: 'read_intelligence_dashboard',
    name: 'Read intelligence dashboard',
    description: 'Read the AURA business intelligence dashboard summary.',
    category: 'intelligence',
    requiredPermissions: ['intelligence:read', 'agents:read'],
    executable: true,
  },
  {
    toolKey: 'read_recommendations',
    name: 'Read recommendations',
    description: 'Read AI-generated business recommendations.',
    category: 'intelligence',
    requiredPermissions: ['intelligence:read', 'agents:read'],
    executable: true,
  },
  {
    toolKey: 'read_memory',
    name: 'Read company memory',
    description: 'Read saved business rules and preferences.',
    category: 'intelligence',
    requiredPermissions: ['intelligence:read'],
    executable: true,
  },
  {
    toolKey: 'store_memory',
    name: 'Store company memory',
    description: 'Save a business rule or preference for future reference (requires approval).',
    category: 'intelligence',
    requiredPermissions: ['intelligence:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'analyze_cash_flow',
    name: 'Analyze cash flow',
    description: 'Summarize revenue, outstanding invoices, and payment trends.',
    category: 'finance',
    requiredPermissions: ['finance:read'],
    executable: true,
  },
  {
    toolKey: 'read_analytics_dashboard',
    name: 'Read analytics dashboard',
    description: 'Read executive analytics dashboard with revenue, jobs, customers, and KPIs.',
    category: 'analytics',
    requiredPermissions: ['analytics:read'],
    executable: true,
  },
  {
    toolKey: 'read_analytics_profitability',
    name: 'Read job profitability',
    description: 'Analyze job revenue and estimated profitability from real tenant data.',
    category: 'analytics',
    requiredPermissions: ['analytics:read'],
    executable: true,
  },
  {
    toolKey: 'read_cashflow_context',
    name: 'Read cash flow context',
    description: 'Read cash inflow, outflow, position, and forecast intelligence from real tenant data.',
    category: 'finance',
    requiredPermissions: ['finance:read'],
    executable: true,
  },
  {
    toolKey: 'read_profitability_context',
    name: 'Read profitability context',
    description: 'Read profit per job, customer, service, and margin analysis from real tenant data.',
    category: 'finance',
    requiredPermissions: ['finance:read', 'analytics:read'],
    executable: true,
  },
  {
    toolKey: 'read_receivables_context',
    name: 'Read receivables context',
    description: 'Read overdue invoices, payment ageing, and collection priorities from real tenant data.',
    category: 'finance',
    requiredPermissions: ['finance:read'],
    executable: true,
  },
  {
    toolKey: 'read_expense_context',
    name: 'Read expense context',
    description: 'Read expense categories, supplier spending, and spending trends from real tenant data.',
    category: 'finance',
    requiredPermissions: ['finance:read'],
    executable: true,
  },
  {
    toolKey: 'read_budget_context',
    name: 'Read budget context',
    description: 'Read budget summaries and actual vs budget variance from real tenant data.',
    category: 'finance',
    requiredPermissions: ['finance:read'],
    executable: true,
  },
  {
    toolKey: 'read_finance_forecast',
    name: 'Read finance forecast',
    description: 'Read weekly or monthly financial forecast and cash shortage warnings from real tenant data.',
    category: 'finance',
    requiredPermissions: ['finance:read'],
    executable: true,
  },
  {
    toolKey: 'draft_finance_action',
    name: 'Draft finance action',
    description: 'Draft a finance action for review (requires approval). No automatic payments or accounting changes.',
    category: 'finance',
    requiredPermissions: ['finance:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'read_technician_performance',
    name: 'Read technician performance',
    description: 'Read technician workload, completion counts, and efficiency trends.',
    category: 'analytics',
    requiredPermissions: ['analytics:read'],
    executable: true,
  },
  {
    toolKey: 'read_customer_analytics',
    name: 'Read customer analytics',
    description: 'Read customer growth, repeat business, quote conversion, and value trends.',
    category: 'analytics',
    requiredPermissions: ['analytics:read'],
    executable: true,
  },
  {
    toolKey: 'read_mobile_context',
    name: 'Read mobile context',
    description: 'Read mobile-optimised owner, technician, or customer business context summary.',
    category: 'mobile',
    requiredPermissions: ['mobile:read'],
    executable: true,
  },
  {
    toolKey: 'read_orchestration_status',
    name: 'Read orchestration status',
    description: 'Read active agent orchestrations, workflow runs, pending approvals, and recent execution history.',
    category: 'orchestration',
    requiredPermissions: ['orchestration:read'],
    executable: true,
  },
  {
    toolKey: 'read_sales_context',
    name: 'Read sales context',
    description: 'Read sales intelligence context including pipeline value, open opportunities, and detected signals.',
    category: 'sales',
    requiredPermissions: ['sales:read'],
    executable: true,
  },
  {
    toolKey: 'read_opportunities',
    name: 'Read sales opportunities',
    description: 'Read detected and tracked sales opportunities from real tenant CRM, jobs, and finance data.',
    category: 'sales',
    requiredPermissions: ['sales:read'],
    executable: true,
  },
  {
    toolKey: 'read_sales_pipeline',
    name: 'Read sales pipeline',
    description: 'Read sales pipeline stages, metrics, and conversion performance.',
    category: 'sales',
    requiredPermissions: ['sales:read'],
    executable: true,
  },
  {
    toolKey: 'draft_sales_follow_up',
    name: 'Draft sales follow-up',
    description: 'Draft a sales follow-up recommendation or communication for review (requires approval).',
    category: 'sales',
    requiredPermissions: ['sales:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'draft_quote_recommendation',
    name: 'Draft quote recommendation',
    description: 'Draft quote preparation recommendations based on customer history (requires approval).',
    category: 'sales',
    requiredPermissions: ['sales:write', 'finance:read'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'read_marketing_context',
    name: 'Read marketing context',
    description: 'Read marketing intelligence context including segments, campaigns, and recommendations.',
    category: 'marketing',
    requiredPermissions: ['marketing:read'],
    executable: true,
  },
  {
    toolKey: 'read_customer_segments',
    name: 'Read customer segments',
    description: 'Read computed and stored customer marketing segments from real tenant data.',
    category: 'marketing',
    requiredPermissions: ['marketing:read'],
    executable: true,
  },
  {
    toolKey: 'read_marketing_activity',
    name: 'Read marketing activity',
    description: 'Read marketing campaign and content activity history.',
    category: 'marketing',
    requiredPermissions: ['marketing:read'],
    executable: true,
  },
  {
    toolKey: 'draft_marketing_campaign',
    name: 'Draft marketing campaign',
    description: 'Draft a marketing campaign proposal for review (requires approval).',
    category: 'marketing',
    requiredPermissions: ['marketing:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'draft_marketing_content',
    name: 'Draft marketing content',
    description: 'Draft marketing content or messaging for review (requires approval).',
    category: 'marketing',
    requiredPermissions: ['marketing:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'read_lead_context',
    name: 'Read lead context',
    description: 'Read lead generation context including active leads, scores, and acquisition summary.',
    category: 'leads',
    requiredPermissions: ['leads:read'],
    executable: true,
  },
  {
    toolKey: 'read_lead_pipeline',
    name: 'Read lead pipeline',
    description: 'Read lead pipeline stages, counts, and conversion metrics.',
    category: 'leads',
    requiredPermissions: ['leads:read'],
    executable: true,
  },
  {
    toolKey: 'score_lead',
    name: 'Score lead',
    description: 'Analyze and score a lead using real CRM, job, quote, and communication signals.',
    category: 'leads',
    requiredPermissions: ['leads:read'],
    executable: true,
  },
  {
    toolKey: 'read_acquisition_insights',
    name: 'Read acquisition insights',
    description: 'Read acquisition intelligence insights derived from real tenant lead and CRM data.',
    category: 'leads',
    requiredPermissions: ['leads:read'],
    executable: true,
  },
  {
    toolKey: 'draft_lead_follow_up',
    name: 'Draft lead follow-up',
    description: 'Draft a lead follow-up task or communication for review (requires approval).',
    category: 'leads',
    requiredPermissions: ['leads:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'draft_lead_handoff',
    name: 'Draft sales handoff',
    description: 'Draft a sales handoff recommendation for review (requires approval).',
    category: 'leads',
    requiredPermissions: ['leads:write', 'sales:read'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'read_voice_context',
    name: 'Read voice context',
    description: 'Read voice receptionist context including active sessions, follow-ups, and waiting enquiries.',
    category: 'voice',
    requiredPermissions: ['voice:read'],
    executable: true,
  },
  {
    toolKey: 'read_call_history',
    name: 'Read call history',
    description: 'Read voice session and call history from real tenant records.',
    category: 'voice',
    requiredPermissions: ['voice:read'],
    executable: true,
  },
  {
    toolKey: 'summarize_call',
    name: 'Summarize call',
    description: 'Summarize a voice session from recorded conversation turns and session data.',
    category: 'voice',
    requiredPermissions: ['voice:read'],
    executable: true,
  },
  {
    toolKey: 'draft_follow_up_from_call',
    name: 'Draft follow-up from call',
    description: 'Draft a follow-up action from a voice session for review (requires approval).',
    category: 'voice',
    requiredPermissions: ['voice:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'draft_appointment_request_from_call',
    name: 'Draft appointment request',
    description: 'Draft an appointment booking request from a call for review (requires approval).',
    category: 'voice',
    requiredPermissions: ['voice:write', 'dispatch:read'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'draft_lead_from_call',
    name: 'Draft lead from call',
    description: 'Draft a lead record from a voice enquiry for review (requires approval).',
    category: 'voice',
    requiredPermissions: ['voice:write', 'leads:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'draft_customer_note_from_call',
    name: 'Draft customer note from call',
    description: 'Draft a CRM customer note from a voice session for review (requires approval).',
    category: 'voice',
    requiredPermissions: ['voice:write', 'customers:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'read_customer_support_context',
    name: 'Read customer support context',
    description: 'Read customer support context including open conversations, escalations, and attention insights.',
    category: 'customer_support',
    requiredPermissions: ['customer_support:read'],
    executable: true,
  },
  {
    toolKey: 'read_customer_conversation',
    name: 'Read customer conversation',
    description: 'Read support conversation history and messages for an authorised customer.',
    category: 'customer_support',
    requiredPermissions: ['customer_support:read'],
    executable: true,
  },
  {
    toolKey: 'read_customer_job_status',
    name: 'Read customer job status',
    description: 'Read job, invoice, and quote status for an authorised customer.',
    category: 'customer_support',
    requiredPermissions: ['customer_support:read', 'jobs:read'],
    executable: true,
  },
  {
    toolKey: 'draft_customer_response',
    name: 'Draft customer response',
    description: 'Draft a customer support response for review (requires approval).',
    category: 'customer_support',
    requiredPermissions: ['customer_support:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'draft_appointment_update',
    name: 'Draft appointment update',
    description: 'Draft an appointment update message for a customer for review (requires approval).',
    category: 'customer_support',
    requiredPermissions: ['customer_support:write', 'dispatch:read'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'draft_invoice_explanation',
    name: 'Draft invoice explanation',
    description: 'Draft an invoice explanation for a customer for review (requires approval).',
    category: 'customer_support',
    requiredPermissions: ['customer_support:write', 'finance:read'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'draft_service_information_response',
    name: 'Draft service information response',
    description: 'Draft a service information response for a customer for review (requires approval).',
    category: 'customer_support',
    requiredPermissions: ['customer_support:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'read_customer_dashboard',
    name: 'Read customer dashboard',
    description: 'Read unified customer portal dashboard data for a linked customer account.',
    category: 'customer_support',
    requiredPermissions: ['portal:read', 'customers:read'],
    executable: true,
  },
  {
    toolKey: 'read_customer_jobs',
    name: 'Read customer jobs',
    description: 'Read customer-facing job tracking data without internal notes.',
    category: 'customer_support',
    requiredPermissions: ['portal:read', 'jobs:read'],
    executable: true,
  },
  {
    toolKey: 'read_customer_finances',
    name: 'Read customer finances',
    description: 'Read customer invoice, quote, and payment centre data (read-only).',
    category: 'customer_support',
    requiredPermissions: ['portal:read', 'finance:read'],
    executable: true,
  },
  {
    toolKey: 'read_customer_notifications',
    name: 'Read customer notifications',
    description: 'Read customer portal notifications for a linked portal user.',
    category: 'customer_support',
    requiredPermissions: ['portal:read'],
    executable: true,
  },
  {
    toolKey: 'search_customer_knowledge',
    name: 'Search customer knowledge',
    description: 'Search customer-visible knowledge articles and SOPs.',
    category: 'customer_support',
    requiredPermissions: ['portal:read', 'knowledge:read'],
    executable: true,
  },
  {
    toolKey: 'draft_customer_request',
    name: 'Draft customer request',
    description: 'Draft a customer portal request for review (requires approval before execution).',
    category: 'customer_support',
    requiredPermissions: ['portal:read', 'customer_support:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'read_mobile_dashboard',
    name: 'Read mobile dashboard',
    description: 'Read the technician mobile workforce dashboard for the current user.',
    category: 'operations',
    requiredPermissions: ['mobile:read', 'jobs:read'],
    executable: true,
  },
  {
    toolKey: 'read_mobile_jobs',
    name: 'Read mobile jobs',
    description: 'Read assigned jobs for the current technician.',
    category: 'operations',
    requiredPermissions: ['mobile:read', 'jobs:read'],
    executable: true,
  },
  {
    toolKey: 'read_mobile_route',
    name: 'Read mobile route',
    description: 'Read route intelligence, GPS, and travel history for the current technician.',
    category: 'operations',
    requiredPermissions: ['mobile:read', 'fleet:read', 'dispatch:read'],
    executable: true,
  },
  {
    toolKey: 'read_mobile_inventory',
    name: 'Read mobile inventory',
    description: 'Read inventory alerts and recent usage for the current technician.',
    category: 'operations',
    requiredPermissions: ['mobile:read', 'inventory:read'],
    executable: true,
  },
  {
    toolKey: 'read_mobile_notifications',
    name: 'Read mobile notifications',
    description: 'Read technician mobile notifications.',
    category: 'operations',
    requiredPermissions: ['mobile:read'],
    executable: true,
  },
  {
    toolKey: 'draft_mobile_request',
    name: 'Draft mobile request',
    description: 'Draft a mobile workforce request for review (requires approval before execution).',
    category: 'operations',
    requiredPermissions: ['mobile:read', 'mobile:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'read_comeback_history',
    name: 'Read comeback history',
    description: 'Read quality comeback and callback history for the tenant.',
    category: 'quality',
    requiredPermissions: ['quality:read', 'executive:read'],
    executable: true,
  },
  {
    toolKey: 'read_quality_score',
    name: 'Read quality score',
    description: 'Read first-time fix rate, quality score, and quality cost summary.',
    category: 'quality',
    requiredPermissions: ['quality:read', 'executive:read'],
    executable: true,
  },
  {
    toolKey: 'read_root_cause_analysis',
    name: 'Read root cause analysis',
    description: 'Read root cause classification for a comeback (AURA recommendations are non-binding).',
    category: 'quality',
    requiredPermissions: ['quality:read', 'executive:read'],
    executable: true,
  },
  {
    toolKey: 'read_warranty_history',
    name: 'Read warranty history',
    description: 'Read warranty claims and visit history.',
    category: 'quality',
    requiredPermissions: ['quality:read', 'executive:read'],
    executable: true,
  },
  {
    toolKey: 'read_supplier_quality',
    name: 'Read supplier quality',
    description: 'Read supplier defect intelligence and recurring failure trends.',
    category: 'quality',
    requiredPermissions: ['quality:read', 'procurement:read'],
    executable: true,
  },
  {
    toolKey: 'draft_quality_action',
    name: 'Draft quality action',
    description: 'Draft a technician accountability action for manager approval (no automatic penalties).',
    category: 'quality',
    requiredPermissions: ['quality:read', 'quality:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'draft_quality_review',
    name: 'Draft quality review',
    description: 'Draft a quality investigation review for approval.',
    category: 'quality',
    requiredPermissions: ['quality:read', 'quality:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'draft_payroll_recommendation',
    name: 'Draft payroll recommendation',
    description: 'Draft a payroll/labour recovery recommendation for approval (never executes payroll changes).',
    category: 'quality',
    requiredPermissions: ['quality:read', 'quality:write', 'finance:read'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'read_customer_communications',
    name: 'Read customer communications',
    description: 'Read unified customer communication timeline across calls, WhatsApp, email, SMS, portal, and support.',
    category: 'communications_intelligence',
    requiredPermissions: ['communications_intelligence:read', 'communications:read'],
    executable: true,
  },
  {
    toolKey: 'read_conversation_summary',
    name: 'Read conversation summary',
    description: 'Read AI conversation intelligence summaries including sentiment and follow-up recommendations.',
    category: 'communications_intelligence',
    requiredPermissions: ['communications_intelligence:read', 'customer_support:read'],
    executable: true,
  },
  {
    toolKey: 'read_whatsapp_history',
    name: 'Read WhatsApp history',
    description: 'Read WhatsApp conversation history with delivery and read status.',
    category: 'communications_intelligence',
    requiredPermissions: ['communications_intelligence:read', 'communications:read'],
    executable: true,
  },
  {
    toolKey: 'read_email_threads',
    name: 'Read email threads',
    description: 'Read email thread intelligence grouped from real CRM communications.',
    category: 'communications_intelligence',
    requiredPermissions: ['communications_intelligence:read', 'communications:read'],
    executable: true,
  },
  {
    toolKey: 'read_sms_history',
    name: 'Read SMS history',
    description: 'Read SMS delivery and reply history.',
    category: 'communications_intelligence',
    requiredPermissions: ['communications_intelligence:read', 'communications:read'],
    executable: true,
  },
  {
    toolKey: 'draft_customer_reply',
    name: 'Draft customer reply',
    description: 'Draft a customer reply for approval (never sends automatically).',
    category: 'communications_intelligence',
    requiredPermissions: ['communications_intelligence:read', 'communications_intelligence:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'draft_follow_up',
    name: 'Draft follow-up',
    description: 'Draft a communication follow-up for approval (never contacts customer automatically).',
    category: 'communications_intelligence',
    requiredPermissions: ['communications_intelligence:read', 'communications_intelligence:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'read_asset_register',
    name: 'Read asset register',
    description: 'Read the asset and equipment register for the tenant.',
    category: 'asset_equipment',
    requiredPermissions: ['asset_equipment:read', 'fleet:read'],
    executable: true,
  },
  {
    toolKey: 'read_asset_history',
    name: 'Read asset history',
    description: 'Read asset lifecycle history including acquisition, maintenance, and disposal.',
    category: 'asset_equipment',
    requiredPermissions: ['asset_equipment:read', 'fleet:read'],
    executable: true,
  },
  {
    toolKey: 'read_maintenance_schedule',
    name: 'Read maintenance schedule',
    description: 'Read preventative maintenance schedules and due dates.',
    category: 'asset_equipment',
    requiredPermissions: ['asset_equipment:read', 'fleet:read'],
    executable: true,
  },
  {
    toolKey: 'read_asset_performance',
    name: 'Read asset performance',
    description: 'Read asset performance analytics including cost, downtime, and reliability.',
    category: 'asset_equipment',
    requiredPermissions: ['asset_equipment:read', 'fleet:read'],
    executable: true,
  },
  {
    toolKey: 'read_inspection_history',
    name: 'Read inspection history',
    description: 'Read safety, vehicle, equipment, and compliance inspection history.',
    category: 'asset_equipment',
    requiredPermissions: ['asset_equipment:read', 'fleet:read'],
    executable: true,
  },
  {
    toolKey: 'read_calibration_status',
    name: 'Read calibration status',
    description: 'Read calibration and certification expiry status.',
    category: 'asset_equipment',
    requiredPermissions: ['asset_equipment:read', 'fleet:read'],
    executable: true,
  },
  {
    toolKey: 'draft_maintenance_action',
    name: 'Draft maintenance action',
    description: 'Draft a maintenance action for approval (never schedules automatically).',
    category: 'asset_equipment',
    requiredPermissions: ['asset_equipment:read', 'asset_equipment:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'draft_asset_replacement',
    name: 'Draft asset replacement',
    description: 'Draft an asset replacement recommendation for approval (never disposes automatically).',
    category: 'asset_equipment',
    requiredPermissions: ['asset_equipment:read', 'asset_equipment:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'read_ai_provider_status',
    name: 'Read AI provider status',
    description: 'Read configured AI provider registry status, health, and availability.',
    category: 'ai_orchestration',
    requiredPermissions: ['ai_orchestration:read', 'agents:read', 'executive:read'],
    executable: true,
  },
  {
    toolKey: 'read_ai_capabilities',
    name: 'Read AI capabilities',
    description: 'Read model capability metadata used by the routing engine.',
    category: 'ai_orchestration',
    requiredPermissions: ['ai_orchestration:read', 'agents:read', 'executive:read'],
    executable: true,
  },
  {
    toolKey: 'read_ai_costs',
    name: 'Read AI costs',
    description: 'Read token usage and provider cost analytics from real tenant data.',
    category: 'ai_orchestration',
    requiredPermissions: ['ai_orchestration:read', 'agents:read', 'executive:read'],
    executable: true,
  },
  {
    toolKey: 'read_ai_quality',
    name: 'Read AI quality',
    description: 'Read AI quality evaluations, feedback, and response metrics.',
    category: 'ai_orchestration',
    requiredPermissions: ['ai_orchestration:read', 'agents:read', 'executive:read'],
    executable: true,
  },
  {
    toolKey: 'read_ai_routing',
    name: 'Read AI routing',
    description: 'Read multi-model routing rules, fallback chains, and routing statistics.',
    category: 'ai_orchestration',
    requiredPermissions: ['ai_orchestration:read', 'agents:read', 'executive:read'],
    executable: true,
  },
  {
    toolKey: 'read_prompt_versions',
    name: 'Read prompt versions',
    description: 'Read centralized prompt templates and version history.',
    category: 'ai_orchestration',
    requiredPermissions: ['ai_orchestration:read', 'agents:read', 'executive:read'],
    executable: true,
  },
  {
    toolKey: 'draft_prompt_update',
    name: 'Draft prompt update',
    description: 'Draft a prompt update for approval (never publishes automatically).',
    category: 'ai_orchestration',
    requiredPermissions: ['ai_orchestration:read', 'ai_orchestration:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'draft_provider_configuration',
    name: 'Draft provider configuration',
    description: 'Draft an AI provider configuration change for approval (never applies automatically).',
    category: 'ai_orchestration',
    requiredPermissions: ['ai_orchestration:read', 'ai_orchestration:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'read_dispatch_dashboard',
    name: 'Read dispatch dashboard',
    description: 'Read live dispatch command centre dashboard including workload and queue status.',
    category: 'dispatch_intelligence',
    requiredPermissions: ['dispatch_intelligence:read', 'dispatch:read', 'agents:read'],
    executable: true,
  },
  {
    toolKey: 'read_call_queue',
    name: 'Read call queue',
    description: 'Read live call queue analytics from real tenant communication records.',
    category: 'dispatch_intelligence',
    requiredPermissions: ['dispatch_intelligence:read', 'dispatch:read', 'voice:read'],
    executable: true,
  },
  {
    toolKey: 'read_technician_matching',
    name: 'Read technician matching',
    description: 'Read technician matching recommendations using skills, workload, and quality data.',
    category: 'dispatch_intelligence',
    requiredPermissions: ['dispatch_intelligence:read', 'dispatch:read', 'jobs:read'],
    executable: true,
  },
  {
    toolKey: 'read_dispatch_recommendations',
    name: 'Read dispatch recommendations',
    description: 'Read dispatch recommendations for reassignment, workload balancing, and emergencies.',
    category: 'dispatch_intelligence',
    requiredPermissions: ['dispatch_intelligence:read', 'dispatch:read'],
    executable: true,
  },
  {
    toolKey: 'read_callback_queue',
    name: 'Read callback queue',
    description: 'Read customer callback queue and missed call tracking.',
    category: 'dispatch_intelligence',
    requiredPermissions: ['dispatch_intelligence:read', 'dispatch:read', 'voice:read'],
    executable: true,
  },
  {
    toolKey: 'read_emergency_dispatch',
    name: 'Read emergency dispatch',
    description: 'Read emergency dispatch assessments and escalation recommendations.',
    category: 'dispatch_intelligence',
    requiredPermissions: ['dispatch_intelligence:read', 'dispatch:read'],
    executable: true,
  },
  {
    toolKey: 'draft_dispatch_action',
    name: 'Draft dispatch action',
    description: 'Draft a dispatch action for approval (never assigns technicians automatically).',
    category: 'dispatch_intelligence',
    requiredPermissions: ['dispatch_intelligence:read', 'dispatch_intelligence:write', 'dispatch:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'draft_callback_action',
    name: 'Draft callback action',
    description: 'Draft a customer callback action for approval (never contacts customer automatically).',
    category: 'dispatch_intelligence',
    requiredPermissions: ['dispatch_intelligence:read', 'dispatch_intelligence:write', 'voice:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'read_fleet_dashboard',
    name: 'Read fleet dashboard',
    description: 'Read fleet executive dashboard with utilization, costs, health score, and GPS status.',
    category: 'fleet_intelligence',
    requiredPermissions: ['fleet_intelligence:read', 'fleet:read', 'agents:read'],
    executable: true,
  },
  {
    toolKey: 'read_trip_history',
    name: 'Read trip history',
    description: 'Read GPS-derived trip history from real Cartrack position data (never fabricated).',
    category: 'fleet_intelligence',
    requiredPermissions: ['fleet_intelligence:read', 'fleet:read', 'integrations:read'],
    executable: true,
  },
  {
    toolKey: 'read_monthly_trip_report',
    name: 'Read monthly trip report',
    description: 'Read generated monthly trip reports with export metadata for PDF/Excel.',
    category: 'fleet_intelligence',
    requiredPermissions: ['fleet_intelligence:read', 'fleet:read'],
    executable: true,
  },
  {
    toolKey: 'read_driver_behaviour',
    name: 'Read driver behaviour',
    description: 'Read driver behaviour events analysed from real GPS telemetry.',
    category: 'fleet_intelligence',
    requiredPermissions: ['fleet_intelligence:read', 'fleet:read', 'integrations:read'],
    executable: true,
  },
  {
    toolKey: 'read_vehicle_utilization',
    name: 'Read vehicle utilization',
    description: 'Read vehicle utilization analytics including downtime and jobs completed.',
    category: 'fleet_intelligence',
    requiredPermissions: ['fleet_intelligence:read', 'fleet:read'],
    executable: true,
  },
  {
    toolKey: 'read_fleet_costs',
    name: 'Read fleet costs',
    description: 'Read fleet operating costs and cost analytics from tenant-recorded data.',
    category: 'fleet_intelligence',
    requiredPermissions: ['fleet_intelligence:read', 'fleet:read'],
    executable: true,
  },
  {
    toolKey: 'draft_fleet_action',
    name: 'Draft fleet action',
    description: 'Draft a fleet action for approval (never executes maintenance or reassignment automatically).',
    category: 'fleet_intelligence',
    requiredPermissions: ['fleet_intelligence:read', 'fleet_intelligence:write', 'fleet:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'draft_vehicle_replacement',
    name: 'Draft vehicle replacement',
    description: 'Draft a vehicle replacement recommendation for approval (never replaces vehicles automatically).',
    category: 'fleet_intelligence',
    requiredPermissions: ['fleet_intelligence:read', 'fleet_intelligence:write', 'fleet:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'read_personal_communications_dashboard',
    name: 'Read personal communications dashboard',
    description: 'Read executive personal/business communications dashboard from real tenant data.',
    category: 'personal_communications',
    requiredPermissions: ['personal_communications:read', 'communications_intelligence:read', 'agents:read'],
    executable: true,
  },
  {
    toolKey: 'read_business_conversations',
    name: 'Read business conversations',
    description: 'Read indexed business WhatsApp conversations with privacy boundaries applied.',
    category: 'personal_communications',
    requiredPermissions: ['personal_communications:read', 'communications:read'],
    executable: true,
  },
  {
    toolKey: 'read_voice_note_summary',
    name: 'Read voice note summary',
    description: 'Read voice note transcription and summarization results (never fabricated).',
    category: 'personal_communications',
    requiredPermissions: ['personal_communications:read', 'communications_intelligence:read'],
    executable: true,
  },
  {
    toolKey: 'read_media_analysis',
    name: 'Read media analysis',
    description: 'Read image, video, and document analysis recommendations from real media records.',
    category: 'personal_communications',
    requiredPermissions: ['personal_communications:read', 'communications_intelligence:read'],
    executable: true,
  },
  {
    toolKey: 'read_follow_up_queue',
    name: 'Read follow-up queue',
    description: 'Read communication follow-up queue including awaiting replies and missed calls.',
    category: 'personal_communications',
    requiredPermissions: ['personal_communications:read', 'communications_intelligence:read'],
    executable: true,
  },
  {
    toolKey: 'read_communication_classification',
    name: 'Read communication classification',
    description: 'Read conversation classification results with confidence scores and manual overrides.',
    category: 'personal_communications',
    requiredPermissions: ['personal_communications:read', 'communications:read'],
    executable: true,
  },
  {
    toolKey: 'draft_business_action',
    name: 'Draft business action',
    description: 'Draft a business communication action for approval (never sends messages automatically).',
    category: 'personal_communications',
    requiredPermissions: ['personal_communications:read', 'personal_communications:write', 'communications:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'score_candidates',
    name: 'Score candidates',
    description: 'Analyze recruiting candidates and provide pipeline scoring insights.',
    category: 'recruiting',
    requiredPermissions: ['recruiting:read'],
    executable: true,
  },
  {
    toolKey: 'draft_hiring_recommendation',
    name: 'Draft hiring recommendation',
    description: 'Draft a hiring recommendation for review (requires approval).',
    category: 'recruiting',
    requiredPermissions: ['recruiting:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'read_workforce_context',
    name: 'Read workforce context',
    description: 'Read workforce intelligence context including pipeline, skill gaps, and staffing insights.',
    category: 'workforce',
    requiredPermissions: ['workforce:read', 'recruiting:read'],
    executable: true,
  },
  {
    toolKey: 'read_candidate_pipeline',
    name: 'Read candidate pipeline',
    description: 'Read candidate pipeline stages and counts across the hiring lifecycle.',
    category: 'workforce',
    requiredPermissions: ['workforce:read', 'recruiting:read'],
    executable: true,
  },
  {
    toolKey: 'read_skill_gaps',
    name: 'Read skill gaps',
    description: 'Read employee skill gaps and training need signals.',
    category: 'workforce',
    requiredPermissions: ['workforce:read'],
    executable: true,
  },
  {
    toolKey: 'read_staffing_insights',
    name: 'Read staffing insights',
    description: 'Read staffing requirements, capacity signals, and workforce planning insights.',
    category: 'workforce',
    requiredPermissions: ['workforce:read'],
    executable: true,
  },
  {
    toolKey: 'draft_recruitment_action',
    name: 'Draft recruitment action',
    description: 'Draft a recruitment action for review (requires approval).',
    category: 'workforce',
    requiredPermissions: ['workforce:write', 'recruiting:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'draft_candidate_communication',
    name: 'Draft candidate communication',
    description: 'Draft candidate communication for review (requires approval).',
    category: 'workforce',
    requiredPermissions: ['workforce:write', 'recruiting:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'draft_interview_request',
    name: 'Draft interview request',
    description: 'Draft an interview request for review (requires approval).',
    category: 'workforce',
    requiredPermissions: ['workforce:write', 'recruiting:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'draft_training_plan',
    name: 'Draft training plan',
    description: 'Draft a training plan recommendation for review (requires approval).',
    category: 'workforce',
    requiredPermissions: ['workforce:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'read_procurement_context',
    name: 'Read procurement context',
    description: 'Read procurement intelligence context including stock signals, suppliers, and recommendations.',
    category: 'procurement',
    requiredPermissions: ['procurement:read'],
    executable: true,
  },
  {
    toolKey: 'read_stock_intelligence',
    name: 'Read stock intelligence',
    description: 'Read inventory stock intelligence signals including low stock, fast-moving, and slow-moving items.',
    category: 'procurement',
    requiredPermissions: ['procurement:read', 'inventory:read'],
    executable: true,
  },
  {
    toolKey: 'read_supplier_insights',
    name: 'Read supplier insights',
    description: 'Read supplier performance, cost, and coverage insights.',
    category: 'procurement',
    requiredPermissions: ['procurement:read'],
    executable: true,
  },
  {
    toolKey: 'read_purchase_orders',
    name: 'Read purchase orders',
    description: 'Read purchase order records and lifecycle status.',
    category: 'procurement',
    requiredPermissions: ['procurement:read'],
    executable: true,
  },
  {
    toolKey: 'draft_purchase_order',
    name: 'Draft purchase order',
    description: 'Draft a purchase order for review (requires approval).',
    category: 'procurement',
    requiredPermissions: ['procurement:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'read_business_health',
    name: 'Read business health',
    description: 'Read business health score and component breakdown from real TITAN data.',
    category: 'executive',
    requiredPermissions: ['executive:read', 'intelligence:read'],
    executable: true,
  },
  {
    toolKey: 'read_executive_alerts',
    name: 'Read executive alerts',
    description: 'Read executive intelligence alerts for revenue, capacity, customer, and stock risks.',
    category: 'executive',
    requiredPermissions: ['executive:read'],
    executable: true,
  },
  {
    toolKey: 'read_business_summary',
    name: 'Read business summary',
    description: 'Read executive business performance summary from real operational data.',
    category: 'executive',
    requiredPermissions: ['executive:read', 'intelligence:read'],
    executable: true,
  },
  {
    toolKey: 'read_strategic_recommendations',
    name: 'Read strategic recommendations',
    description: 'Read strategic growth, cost optimisation, and operational recommendations.',
    category: 'executive',
    requiredPermissions: ['executive:read'],
    executable: true,
  },
  {
    toolKey: 'draft_executive_action',
    name: 'Draft executive action',
    description: 'Draft an executive action for review (requires approval).',
    category: 'executive',
    requiredPermissions: ['executive:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'read_knowledge_base',
    name: 'Read knowledge base',
    description: 'Read knowledge base articles, categories, and statistics from user-created content.',
    category: 'knowledge',
    requiredPermissions: ['knowledge:read'],
    executable: true,
  },
  {
    toolKey: 'search_knowledge',
    name: 'Search knowledge',
    description: 'Search SOPs, documentation, training, policies, and knowledge articles with permission-aware results.',
    category: 'knowledge',
    requiredPermissions: ['knowledge:read'],
    executable: true,
  },
  {
    toolKey: 'read_sop',
    name: 'Read SOP',
    description: 'Read standard operating procedures and version history from user-created content.',
    category: 'knowledge',
    requiredPermissions: ['knowledge:read'],
    executable: true,
  },
  {
    toolKey: 'read_training',
    name: 'Read training library',
    description: 'Read training courses, skill paths, and completion records from user-created content.',
    category: 'knowledge',
    requiredPermissions: ['knowledge:read'],
    executable: true,
  },
  {
    toolKey: 'read_company_policy',
    name: 'Read company policy',
    description: 'Read published company policies and compliance documents from user-created content.',
    category: 'knowledge',
    requiredPermissions: ['knowledge:read'],
    executable: true,
  },
  {
    toolKey: 'read_workflows',
    name: 'Read workflows',
    description: 'Read tenant workflow definitions, triggers, actions, and status from the automation studio.',
    category: 'automation',
    requiredPermissions: ['automation:read'],
    executable: true,
  },
  {
    toolKey: 'read_workflow_history',
    name: 'Read workflow history',
    description: 'Read workflow execution history, runs, and audit logs from real executions only.',
    category: 'automation',
    requiredPermissions: ['automation:read'],
    executable: true,
  },
  {
    toolKey: 'validate_workflow',
    name: 'Validate workflow',
    description: 'Validate a workflow definition for missing actions, unsafe loops, and configuration errors.',
    category: 'automation',
    requiredPermissions: ['automation:read'],
    executable: true,
  },
  {
    toolKey: 'simulate_workflow',
    name: 'Simulate workflow',
    description: 'Simulate a workflow run without modifying production data.',
    category: 'automation',
    requiredPermissions: ['automation:write'],
    executable: true,
  },
  {
    toolKey: 'execute_workflow',
    name: 'Execute workflow',
    description: 'Execute an active workflow manually; approval-gated steps pause until approved.',
    category: 'automation',
    requiredPermissions: ['automation:write'],
    executable: true,
  },
  {
    toolKey: 'draft_workflow',
    name: 'Draft workflow',
    description: 'Draft a workflow definition for review (requires approval before activation).',
    category: 'automation',
    requiredPermissions: ['automation:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'read_integrations',
    name: 'Read integrations',
    description: 'Read integration registry entries, connection status, and health from the Integration Hub.',
    category: 'integrations',
    requiredPermissions: ['integrations:read'],
    executable: true,
  },
  {
    toolKey: 'read_api_health',
    name: 'Read API health',
    description: 'Read integration API health snapshots from real connection and sync data.',
    category: 'integrations',
    requiredPermissions: ['integrations:read'],
    executable: true,
  },
  {
    toolKey: 'read_sync_status',
    name: 'Read sync status',
    description: 'Read synchronization manager status including sync jobs and scheduled syncs.',
    category: 'integrations',
    requiredPermissions: ['integrations:read'],
    executable: true,
  },
  {
    toolKey: 'read_webhook_status',
    name: 'Read webhook status',
    description: 'Read webhook delivery history including retries and dead-letter queue entries.',
    category: 'integrations',
    requiredPermissions: ['integrations:read'],
    executable: true,
  },
  {
    toolKey: 'validate_integration',
    name: 'Validate integration',
    description: 'Validate integration configuration locally without modifying production systems or calling external APIs.',
    category: 'integrations',
    requiredPermissions: ['integrations:read'],
    executable: true,
  },
  {
    toolKey: 'draft_integration_action',
    name: 'Draft integration action',
    description: 'Draft an integration management action for review (requires approval before execution).',
    category: 'integrations',
    requiredPermissions: ['integrations:manage'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'read_business_kpis',
    name: 'Read business KPIs',
    description: 'Read configured business KPIs and current values computed from real tenant data.',
    category: 'executive',
    requiredPermissions: ['bi:read', 'intelligence:read'],
    executable: true,
  },
  {
    toolKey: 'read_business_dashboard',
    name: 'Read business dashboard',
    description: 'Read tenant business intelligence dashboards and widget KPI values.',
    category: 'executive',
    requiredPermissions: ['bi:read', 'intelligence:read'],
    executable: true,
  },
  {
    toolKey: 'read_business_reports',
    name: 'Read business reports',
    description: 'Read saved and scheduled business intelligence reports (metadata only until generated).',
    category: 'executive',
    requiredPermissions: ['bi:read', 'intelligence:read'],
    executable: true,
  },
  {
    toolKey: 'read_business_insights',
    name: 'Read business insights',
    description: 'Read AI-generated business insights from real operational data.',
    category: 'executive',
    requiredPermissions: ['bi:read', 'intelligence:read'],
    executable: true,
  },
  {
    toolKey: 'read_predictive_forecasts',
    name: 'Read predictive forecasts',
    description: 'Read predictive analytics forecasts generated from historical tenant data.',
    category: 'executive',
    requiredPermissions: ['bi:read', 'intelligence:read'],
    executable: true,
  },
  {
    toolKey: 'draft_business_report',
    name: 'Draft business report',
    description: 'Draft a business intelligence report for review (requires approval before generation).',
    category: 'executive',
    requiredPermissions: ['bi:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'draft_knowledge_article',
    name: 'Draft knowledge article',
    description: 'Draft a knowledge article for review (requires approval before publish).',
    category: 'knowledge',
    requiredPermissions: ['knowledge:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'draft_message',
    name: 'Draft message',
    description: 'Draft a generic message outline without sending.',
    category: 'communications',
    requiredPermissions: ['communications:read'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'read_security_dashboard',
    name: 'Read security dashboard',
    description: 'Read tenant security score, sessions, risk alerts, compliance, and encryption status from real activity.',
    category: 'security',
    requiredPermissions: ['security:read', 'agents:read'],
    executable: true,
  },
  {
    toolKey: 'read_audit_logs',
    name: 'Read audit logs',
    description: 'Read immutable central audit logs for the tenant.',
    category: 'security',
    requiredPermissions: ['security:read'],
    executable: true,
  },
  {
    toolKey: 'read_active_sessions',
    name: 'Read active sessions',
    description: 'Read active authenticated sessions for the tenant.',
    category: 'security',
    requiredPermissions: ['security:read'],
    executable: true,
  },
  {
    toolKey: 'read_risk_alerts',
    name: 'Read risk alerts',
    description: 'Read unresolved and recent security risk alerts derived from real tenant activity.',
    category: 'security',
    requiredPermissions: ['security:read'],
    executable: true,
  },
  {
    toolKey: 'read_login_events',
    name: 'Read login events',
    description: 'Read login, logout, and suspicious authentication events.',
    category: 'security',
    requiredPermissions: ['security:read'],
    executable: true,
  },
  {
    toolKey: 'draft_security_action',
    name: 'Draft security action',
    description: 'Draft a security recommendation for approval. Never executes lockouts, deletions, or permission changes automatically.',
    category: 'security',
    requiredPermissions: ['security:read', 'security:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'read_integration_platform_dashboard',
    name: 'Read integration platform dashboard',
    description: 'Read enterprise integration hub dashboard with connector status, monitoring, and vault summary from real tenant data.',
    category: 'integrations',
    requiredPermissions: ['integrations:read', 'agents:read'],
    executable: true,
  },
  {
    toolKey: 'read_integration_connectors',
    name: 'Read integration connectors',
    description: 'Read universal connector registry entries and live connection status for the tenant.',
    category: 'integrations',
    requiredPermissions: ['integrations:read'],
    executable: true,
  },
  {
    toolKey: 'draft_integration_repair',
    name: 'Draft integration repair',
    description: 'Draft an integration repair recommendation for approval. Never reconnects or changes credentials automatically.',
    category: 'integrations',
    requiredPermissions: ['integrations:read', 'integrations:manage'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'read_enterprise_analytics_dashboard',
    name: 'Read enterprise analytics dashboard',
    description: 'Read unified enterprise analytics dashboard with KPIs, warehouse snapshots, forecasts, and governance from real tenant data.',
    category: 'analytics',
    requiredPermissions: ['bi:read', 'analytics:read'],
    executable: true,
  },
  {
    toolKey: 'read_data_warehouse',
    name: 'Read data warehouse',
    description: 'Read analytics data warehouse module summaries, historical snapshots, and data lineage.',
    category: 'analytics',
    requiredPermissions: ['bi:read', 'analytics:read'],
    executable: true,
  },
  {
    toolKey: 'read_analytics_governance',
    name: 'Read analytics governance',
    description: 'Read dataset permissions, report permissions, retention policies, and analytics access audit history.',
    category: 'analytics',
    requiredPermissions: ['bi:read', 'analytics:read'],
    executable: true,
  },
  {
    toolKey: 'draft_strategic_report',
    name: 'Draft strategic report',
    description: 'Draft a strategic business report for executive review (requires approval before generation or distribution).',
    category: 'analytics',
    requiredPermissions: ['bi:write'],
    executable: true,
    requiresApproval: true,
  },
  {
    toolKey: 'read_automation_studio_dashboard',
    name: 'Read automation studio dashboard',
    description: 'Read enterprise automation studio dashboard with workflow health, monitoring, and recommendations from real tenant data.',
    category: 'automation',
    requiredPermissions: ['automation:read'],
    executable: true,
  },
  {
    toolKey: 'read_automation_monitoring',
    name: 'Read automation monitoring',
    description: 'Read workflow execution monitoring — running, completed, failed runs, queue depth, and performance metrics.',
    category: 'automation',
    requiredPermissions: ['automation:read'],
    executable: true,
  },
  {
    toolKey: 'draft_workflow_improvement',
    name: 'Draft workflow improvement',
    description: 'Draft a workflow improvement recommendation for approval. Never publishes or executes workflows automatically.',
    category: 'automation',
    requiredPermissions: ['automation:write'],
    executable: true,
    requiresApproval: true,
  },
];

export type AgentProfileSummary = {
  id: string;
  agentKey: AgentKey;
  registryName: string;
  name: string;
  description: string | null;
  status: AgentProfileStatus;
  permissionCount: number;
  enabledToolCount: number;
  executionCount: number;
  foundationOnly: boolean;
  createdByUserId: string;
  createdByName: string;
  createdAt: string;
  updatedAt: string;
};

export type AgentProfileToolSummary = {
  toolKey: string;
  name: string;
  description: string;
  category: string;
  enabled: boolean;
  config: Record<string, unknown>;
};

export type AgentProfileDetail = AgentProfileSummary & {
  config: Record<string, unknown>;
  permissions: string[];
  tools: AgentProfileToolSummary[];
  registry: AgentRegistryEntry;
};

export type AgentExecutionSummary = {
  id: string;
  agentProfileId: string | null;
  agentProfileName: string | null;
  agentKey: AgentKey | null;
  status: AgentExecutionStatus;
  executionMode: AgentExecutionMode;
  inputSummary: string | null;
  outputSummary: string | null;
  errorMessage: string | null;
  startedAt: string;
  completedAt: string | null;
  createdAt: string;
};

export type AgentsStats = {
  configuredProfileCount: number;
  activeProfileCount: number;
  availableAgentCount: number;
  executionCount: number;
};

export type CreateAgentProfileRequest = {
  agentKey: AgentKey;
  name: string;
  description?: string | null;
  status?: AgentProfileStatus;
  config?: Record<string, unknown>;
  permissions?: string[];
  enabledToolKeys?: string[];
};

export type UpdateAgentProfileRequest = {
  name?: string;
  description?: string | null;
  status?: AgentProfileStatus;
  config?: Record<string, unknown>;
};

export type SetAgentProfilePermissionsRequest = {
  permissions: string[];
};

export type SetAgentProfileToolsRequest = {
  tools: Array<{
    toolKey: string;
    enabled: boolean;
    config?: Record<string, unknown>;
  }>;
};

export function getAgentRegistryEntry(agentKey: AgentKey): AgentRegistryEntry | undefined {
  return AGENT_REGISTRY.find((entry) => entry.agentKey === agentKey);
}

export function getAgentToolDefinition(toolKey: string): AgentToolDefinition | undefined {
  return AGENT_TOOL_REGISTRY.find((tool) => tool.toolKey === toolKey);
}
