export const APP_NAME = 'TITAN';
export const AI_NAME = 'AURA';

export type ApiHealthResponse = {
  status: 'ok';
  service: string;
  version: string;
  timestamp: string;
};

export type ApiErrorResponse = {
  error: {
    code: string;
    message: string;
    details?: unknown;
  };
};

export type ApiResponse<T> = { data: T } | ApiErrorResponse;

export function isApiError(response: ApiResponse<unknown>): response is ApiErrorResponse {
  return 'error' in response;
}

export * from './auth.js';
export * from './cache-keys.js';
export * from './aura.js';
export * from './aura-routing-diagnostics.js';
export * from './company.js';
export * from './young-guns-ops.js';
export * from './localisation.js';
export * from './team.js';
export * from './crm.js';
export * from './contact-validation.js';
export * from './job-contract.js';
export * from './job-execution.js';
export * from './jobs.js';
export * from './job-completion-guards.js';
export * from './scheduling.js';
export * from './finance.js';
export * from './job-payment-ledger.js';
export * from './inventory.js';
export * from './fleet.js';
export * from './fleet-tracking.js';
export * from './integrations.js';
export * from './integration-capability.js';
export * from './marketing-eligibility.js';
export * from './communications.js';
export * from './documents.js';
export * from './automation.js';
export * from './n8n-orchestration.js';
export * from './enterprise-modules.js';
export * from './agents.js';
export * from './tenant-capabilities.js';
export * from './tenant-capability-routing.js';
export * from './portal.js';
export * from './role-experience.js';
export * from './xero-sync.js';
export * from './whatsapp.js';
export * from './agent-runtime.js';
export * from './recruiting.js';
export * from './intelligence.js';
export * from './mobile.js';
export * from './analytics.js';
export * from './agent-orchestration.js';
export * from './sales.js';
export * from './marketing.js';
export * from './leads.js';
export * from './voice.js';
export * from './customer-support.js';
export * from './workforce.js';
export * from './procurement.js';
export * from './executive.js';
export * from './finance-intelligence.js';
export * from './knowledge.js';
export * from './business-intelligence.js';
export * from './integration-api-management.js';
export * from './portal-experience.js';
export * from './mobile-workforce.js';
export * from './job-evidence.js';
export * from './quality-assurance.js';
export * from './communications-intelligence.js';
export * from './asset-equipment.js';
export * from './ai-orchestration.js';
export * from './dispatch-intelligence.js';
export * from './fleet-intelligence.js';
export * from './personal-communications-intelligence.js';
export * from './enterprise-security.js';
export * from './integration-platform.js';
export * from './enterprise-analytics.js';
export * from './enterprise-automation-studio.js';
export * from './enterprise-digital-twin.js';
export * from './enterprise-knowledge-graph.js';
export * from './enterprise-mission-control.js';
export * from './enterprise-evolution.js';
export * from './enterprise-developer-platform.js';
export * from './enterprise-saas-platform.js';
export * from './platform-owner-ai-operations.js';
export * from './unified-ai-orchestration.js';
export * from './enterprise-production-readiness.js';
export * from './enterprise-mobile-platform.js';
export * from './enterprise-unified-communications.js';
export * from './enterprise-customer-experience.js';
export * from './enterprise-asset-lifecycle.js';
export * from './enterprise-workforce-intelligence.js';
export * from './enterprise-legal-compliance.js';
export * from './enterprise-financial-planning.js';
export * from './enterprise-sales-intelligence.js';
export * from './enterprise-marketing-intelligence.js';
export * from './enterprise-service-delivery.js';
export * from './enterprise-it-operations.js';
export * from './enterprise-business-evolution.js';
export * from './enterprise-app-builder.js';
export * from './enterprise-industry-packs.js';
export * from './enterprise-public-developer-platform.js';
export * from './enterprise-saas-management.js';
export * from './enterprise-voice-reception.js';
export * from './enterprise-document-ai.js';
export * from './enterprise-business-continuity.js';
export * from './enterprise-global-search.js';
export * from './enterprise-data-migration.js';
export * from './enterprise-notifications.js';
export * from './enterprise-platform-health.js';
export * from './enterprise-launch-center.js';
export * from './enterprise-release-center.js';
export * from './enterprise-production-launch.js';
export * from './enterprise-release-management.js';
