import { boolean, jsonb, pgEnum, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';
import { agentKeyEnum, agentProfiles } from './agent-profiles';
import { agentRuns } from './agent-runs';
import { companies } from './companies';
import { users } from './users';

export const agentTaskStatusEnum = pgEnum('agent_task_status', [
  'pending_approval',
  'approved',
  'rejected',
  'executed',
  'cancelled',
]);

export const agentTaskTypeEnum = pgEnum('agent_task_type', [
  'create_customer_note',
  'update_job_status',
  'send_whatsapp_draft',
  'create_candidate',
  'update_candidate_status',
  'draft_job_ad',
  'draft_interview_questions',
  'store_memory',
  'draft_hiring_recommendation',
  'draft_sales_follow_up',
  'draft_quote_recommendation',
  'draft_marketing_campaign',
  'draft_marketing_content',
  'draft_lead_follow_up',
  'draft_lead_handoff',
  'draft_follow_up_from_call',
  'draft_appointment_request_from_call',
  'draft_lead_from_call',
  'draft_customer_note_from_call',
  'draft_customer_response',
  'draft_appointment_update',
  'draft_invoice_explanation',
  'draft_service_information_response',
  'draft_recruitment_action',
  'draft_candidate_communication',
  'draft_interview_request',
  'draft_training_plan',
  'draft_purchase_order',
  'draft_executive_action',
  'draft_finance_action',
  'draft_knowledge_article',
  'draft_business_report',
  'draft_workflow',
  'draft_integration_action',
  'draft_customer_request',
  'draft_mobile_request',
  'draft_quality_action',
  'draft_quality_review',
  'draft_payroll_recommendation',
  'draft_customer_reply',
  'draft_follow_up',
  'draft_maintenance_action',
  'draft_asset_replacement',
  'draft_prompt_update',
  'draft_provider_configuration',
  'draft_dispatch_action',
  'draft_callback_action',
  'draft_fleet_action',
  'draft_vehicle_replacement',
  'draft_business_action',
  'draft_security_action',
  'draft_integration_repair',
  'draft_strategic_report',
  'draft_workflow_improvement',
  'draft_decision_report',
  'draft_knowledge_report',
  'draft_executive_briefing',
  'draft_evolution_report',
  'draft_optimization_plan',
  'draft_developer_guide',
  'draft_integration_guide',
  'draft_saas_onboarding_guide',
  'draft_tenant_report',
  'draft_plan_recommendation',
  'draft_recovery_plan',
  'draft_maintenance_plan',
  'draft_operational_report',
  'draft_incident_summary',
  'draft_scaling_recommendation',
  'draft_mobile_report',
  'draft_mobile_quotation',
  'draft_mobile_maintenance_note',
  'draft_mobile_troubleshooting_guide',
  'draft_communications_reply',
  'draft_communications_sms',
  'draft_communications_whatsapp',
  'draft_communications_email',
  'draft_call_summary',
  'draft_follow_up_task',
  'draft_appointment_confirmation',
  'draft_customer_update',
  'draft_cx_support_request',
  'draft_cx_appointment_request',
  'draft_cx_document_request',
  'draft_asset_maintenance_plan',
  'draft_asset_report',
  'draft_asset_customer_explanation',
  'draft_asset_work_order',
  'draft_asset_disposal_request',
  'draft_workforce_onboarding_plan',
  'draft_workforce_development_plan',
  'draft_workforce_performance_report',
  'draft_workforce_hr_communication',
  'draft_workforce_payroll_exception_summary',
  'draft_workforce_offboarding_checklist',
  'draft_workforce_training_recommendation',
  'draft_workforce_technician_match',
  'draft_legal_contract_summary',
  'draft_legal_policy_document',
  'draft_legal_compliance_report',
  'draft_legal_risk_report',
  'draft_legal_matter_summary',
  'draft_legal_customer_notice',
  'draft_legal_supplier_notice',
  'draft_legal_internal_communication',
  'draft_fp_cash_flow_report',
  'draft_fp_budget_commentary',
  'draft_fp_forecast_commentary',
  'draft_fp_profitability_report',
  'draft_fp_payment_plan_proposal',
  'draft_fp_supplier_payment_recommendation',
  'draft_fp_executive_financial_summary',
  'draft_fp_variance_analysis',
  'draft_si_lead_reply',
  'draft_si_follow_up',
  'draft_si_proposal',
  'draft_si_quote_commentary',
  'draft_si_renewal_message',
  'draft_si_account_plan',
  'draft_si_sales_report',
  'draft_si_tender_response',
  'draft_si_executive_revenue_summary',
  'draft_mi_strategy',
  'draft_mi_campaign_plan',
  'draft_mi_social_post',
  'draft_mi_email_campaign',
  'draft_mi_sms_campaign',
  'draft_mi_whatsapp_campaign',
  'draft_mi_ad_copy',
  'draft_mi_video_script',
  'draft_mi_landing_page',
  'draft_mi_blog_content',
  'draft_mi_review_response',
  'draft_mi_campaign_report',
  'draft_mi_executive_marketing_summary',
  'draft_sd_quality_report',
  'draft_sd_corrective_action',
  'draft_sd_customer_summary',
  'draft_sd_sla_report',
  'draft_sd_inspection_summary',
  'draft_sd_warranty_report',
  'draft_sd_callback_analysis',
  'draft_sd_continuous_improvement_plan',
  'draft_sd_executive_service_summary',
  'draft_ito_fix',
  'draft_ito_postmortem',
  'draft_ito_release_notes',
  'draft_ito_infrastructure_report',
  'draft_ito_health_summary',
  'draft_ito_incident_report',
  'draft_ito_change_plan',
  'draft_ito_runbook',
  'draft_ito_rca_report',
  'draft_bev_experiment_plan',
  'draft_bev_improvement_plan',
  'draft_bev_maturity_assessment',
  'draft_bev_benefit_report',
  'draft_bev_lessons_learned',
  'draft_bev_executive_summary',
  'draft_bev_hypothesis',
  'draft_bev_process_report',
  'draft_bev_agent_improvement',
  'draft_ab_implementation_plan',
  'draft_ab_requirements_spec',
  'draft_ab_architecture_impact_report',
  'draft_ab_code_generation_plan',
  'draft_ab_test_plan',
  'draft_ab_deployment_plan',
  'draft_ab_documentation_update',
  'draft_ab_feature_changelog',
  'draft_ab_rollback_plan',
  'draft_ip_job_template',
  'draft_ip_compliance_document',
  'draft_ip_industry_report',
  'draft_ip_workflow',
  'draft_ip_checklist',
  'draft_ip_certificate_template',
  'draft_ip_quote_template',
  'draft_ip_knowledge_article',
  'draft_ip_improvement_plan',
  'draft_pdp_integration_guide',
  'draft_pdp_webhook_config',
  'draft_pdp_api_example',
  'draft_pdp_sdk_example',
  'draft_pdp_diagnostic_report',
  'draft_sm_subscription_report',
  'draft_sm_billing_summary',
  'draft_sm_usage_report',
  'draft_sm_renewal_forecast',
  'draft_sm_plan_recommendation',
  'draft_vr_call_summary',
  'draft_vr_follow_up_tasks',
  'draft_vr_crm_note',
  'draft_vr_job_note',
  'draft_vr_callback_request',
  'draft_vr_lead_creation',
  'draft_vr_appointment_booking',
  'draft_vr_routing_recommendation',
  'draft_dip_extraction_correction',
  'draft_dip_document_summary',
  'draft_dip_workflow_action',
  'draft_dip_compliance_suggestion',
  'draft_dip_supplier_invoice',
  'draft_dip_inventory_receipt',
  'draft_dip_compliance_record',
  'draft_dip_asset_update',
  'draft_dip_warranty_registration',
  'draft_dip_follow_up_task',
  'draft_bc_recovery_plan',
  'draft_bc_verification_report',
  'draft_bc_continuity_improvement',
  'draft_bc_recovery_test_schedule',
  'draft_bc_restore_request',
  'draft_gs_search_report',
  'draft_gs_activity_summary',
  'draft_gs_related_record_recommendation',
  'draft_dm_mapping_suggestion',
  'draft_dm_validation_correction',
  'draft_dm_migration_report',
  'draft_dm_cleanup_recommendation',
  'draft_nc_template',
  'draft_nc_escalation_rule',
  'draft_nc_delivery_report',
  'draft_nc_improvement_recommendation',
  'draft_ph_incident_report',
  'draft_ph_optimization_recommendation',
  'draft_ph_capacity_forecast',
  'draft_ph_diagnostic_summary',
  'draft_lnc_readiness_report',
  'draft_lnc_deployment_plan',
  'draft_lnc_rollout_checklist',
  'draft_lnc_rollback_recommendation',
  'draft_rc_release_notes',
  'draft_rc_optimization_plan',
  'draft_rc_deployment_recommendation',
  'draft_pl_deployment_plan',
  'draft_pl_launch_report',
  'draft_pl_post_launch_checklist',
  'draft_rlm_release_notes',
  'draft_rlm_user_documentation',
  'draft_rlm_admin_documentation',
  'draft_rlm_post_launch_recommendations',
]);

export const agentTasks = pgTable('agent_tasks', {
  id: uuid('id').primaryKey().defaultRandom(),
  companyId: uuid('company_id')
    .notNull()
    .references(() => companies.id, { onDelete: 'cascade' }),
  agentRunId: uuid('agent_run_id').references(() => agentRuns.id, { onDelete: 'set null' }),
  agentProfileId: uuid('agent_profile_id').references(() => agentProfiles.id, {
    onDelete: 'set null',
  }),
  agentKey: agentKeyEnum('agent_key').notNull(),
  userId: uuid('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'no action' }),
  taskType: agentTaskTypeEnum('task_type').notNull(),
  status: agentTaskStatusEnum('status').notNull().default('pending_approval'),
  approvalRequired: boolean('approval_required').notNull().default(true),
  preview: text('preview').notNull(),
  payload: jsonb('payload').$type<Record<string, unknown>>().notNull().default({}),
  result: jsonb('result').$type<Record<string, unknown>>(),
  approvedByUserId: uuid('approved_by_user_id').references(() => users.id, {
    onDelete: 'set null',
  }),
  executedAt: timestamp('executed_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export type AgentTask = typeof agentTasks.$inferSelect;
export type NewAgentTask = typeof agentTasks.$inferInsert;
